qdrant-landing/content/blog/_index.md
qdrant-landing/content/blog/introducing-the-quaterion-a-framework-for-fine-tuning-similarity-learning-models.md
qdrant-landing/content/blog/new-0-7-update-of-the-qdrant-engine-went-live.md
qdrant-landing/content/blog/qdrant-has-joined-nvidia-inception-program.md
qdrant-landing/content/blog/qdrant-v-0-6-0-engine-with-grpc-released.md
qdrant-landing/content/blog/qdrant_and_jina_integration.md
qdrant-landing/content/blog/v0-8-0-update-of-the-qdrant-engine-was-released.md
qdrant-landing/content/blog/v0-9-0-update-of-the-qdrant-engine-went-live.md
qdrant-landing/content/blog/vector-search-and-applications-by-andrey-vasnetsov-cto-at-qdrant.md
qdrant-landing/content/documentation/distributed_deployment.md
qdrant-landing/content/documentation/install.md

Excluded the blog from the sitemap because it still wasn't

Excluded blog from the sitemap

---

qdrant-landing/content/articles/why-rust.md

fix "brough" typo

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/optimizer.md
qdrant-landing/content/documentation/concepts/storage.md
qdrant-landing/content/documentation/guides/quantization.md
qdrant-landing/content/documentation/tutorials/bulk-upload.md

transferred changes from old PR (https://github.com/qdrant/docs/pull/122) over to new docsite + a few more minor changes

update doc as per old commit

---

qdrant-landing/config.toml
qdrant-landing/content/datasets/_index.md
qdrant-landing/content/datasets/common-datasets.md
qdrant-landing/themes/qdrant/layouts/datasets/baseof.html
qdrant-landing/themes/qdrant/layouts/datasets/list.html
qdrant-landing/themes/qdrant/layouts/datasets/single.html
qdrant-landing/themes/qdrant/static/images/icons/download.svg

A new section for the common datasets snapshots.

Add Datasets section

---

.github/workflows/check-dead-links.yml
.github/workflows/internal-dead-links.yml
.lycheeignore
qdrant-landing/config.toml
qdrant-landing/content/datasets/_index.md
qdrant-landing/content/datasets/common-datasets.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/tutorials/_index.md
qdrant-landing/content/documentation/tutorials/q101-getting-started.md
qdrant-landing/content/documentation/tutorials/q101-text-data.md
qdrant-landing/content/legal/terms_cloud.md
qdrant-landing/themes/qdrant/layouts/datasets/baseof.html
qdrant-landing/themes/qdrant/layouts/datasets/list.html
qdrant-landing/themes/qdrant/layouts/datasets/single.html
qdrant-landing/themes/qdrant/layouts/documentation/single.html
qdrant-landing/themes/qdrant/layouts/pricing/list.html
qdrant-landing/themes/qdrant/static/images/icons/download.svg

- changed title of free version from Open Source to Community
- added nodes instead of pods
- tooltips to describe details like HA better
- added calculator link
- some minor details here and there

fix pricing page content / links

---

qdrant-landing/content/documentation/concepts/search.md

also improves by referencing keyword and integer types

Groups: Add index info

---

qdrant-landing/content/documentation/quick-start.md

Adds JS Client to the list of clients

Add JS to list of clients

---

qdrant-landing/content/documentation/guides/configuration.md

- implementing PR https://github.com/qdrant/docs/pull/130
- docs repo is being archived

add configuration handling clarification text

---

qdrant-landing/config.toml
qdrant-landing/content/datasets/_index.md
qdrant-landing/content/datasets/common-datasets.md

removing until more instructions are given

temporarily remove datasets section

---

qdrant-landing/content/documentation/0-dl.md
qdrant-landing/content/documentation/community-links.md
qdrant-landing/content/documentation/overview.md
qdrant-landing/content/documentation/qdrant-alternatives.md
qdrant-landing/content/documentation/release-notes.md

1. Competitor vs Qdrant product analysis in the Getting Started section as per old PR https://github.com/qdrant/docs/pull/102
2. Community Contributions section to aggregate useful content we don't maintain.

Add Competitor Analysis and Community Contributions sections

---

qdrant-landing/content/documentation/cloud/cloud-quick-start.md

-update steps taken to spin up instance, authentication made clearer 
-overall edits and fixes in line with technical writing standards
-will add more images, still a draft

fix qdrant cloud quickstart documentation

---

qdrant-landing/content/documentation/concepts/filtering.md

https://github.com/qdrant/qdrant-client/issues/196

fix: fix nested filter example

---

qdrant-landing/content/documentation/_index.md
qdrant-landing/content/documentation/tutorials/_index.md
qdrant-landing/content/documentation/tutorials/aleph-alpha-search.md
qdrant-landing/content/documentation/tutorials/neural-search.md
qdrant-landing/content/documentation/tutorials/search-beginners.md
qdrant-landing/content/documentation/tutorials/semantic-search-beginners.md

This is a tutorial "for dummies". 
If this format is acceptable, we can extend this to other more complex scenarios.
WIP - still need to clean up the notebook and add some links and fix the navigation.

[WIP] add experimental tutorial

---

qdrant-landing/content/documentation/tutorials/create-snapshot.md

This is a simple tutorial describing creating a snapshot for an existing dataset.

Add a first draft of the "Create Snapshot" tutorial

---

qdrant-landing/content/articles/serverless.md

Someone brought up a wrong link on reddit. This fixes the markdown.

fix link in serverless article

---

qdrant-landing/content/documentation/concepts/indexing.md

A new boolean index has been added in qdrant/qdrant#2174 and  qdrant/qdrant#2107, we just need to also add it to the docs as well

Add bool index

---

qdrant-landing/content/articles/sayt.md

TBD:
- Use new design in images
- Preview image with new style as well
- Icon

review changes for sayt

---

qdrant-landing/content/documentation/overview/qdrant-alternatives.md
qdrant-landing/content/documentation/qdrant-alternatives.md

This PR adds a document comparing Qdrant against Pinecone.
1. Theoretical considerations and concepts
2. Features
3. Migration steps

Pinecone Comparison

---

qdrant-landing/content/articles/search-as-you-type.md

It fixes post description of article located at `qdrant-landing/content/articles/search-as-you-type.md`.
#274 
Please feel free to suggest/modify the description.

Fix incorrect post description

---

qdrant-landing/content/case-studies/bloop.md
qdrant-landing/content/documentation/guides/security.md
qdrant-landing/content/documentation/integrations/langchain.md

Fixes 3 (out of 5) errors reported by the automated link checker.
#262 
The remaining 2 links (403 errors) didn't return any error while I was browsing. Shall we add them to `.lycheeignore`?

fix: fix 404 errors

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/tutorials/multiple-partitions.md

-simplify multiple-partitions.md
-add link to collections.md

simplify multitenancy doc

---

qdrant-landing/content/documentation/concepts/points.md

This describes the 'overwrite payload' action. We have implemented this before but failed to document it.

Document overwrite payload operation

---

qdrant-landing/themes/qdrant/layouts/documentation/baseof.html

Removed excessive empty space at the top of docs section template

---

qdrant-landing/themes/qdrant/layouts/developer/list.html

Small fix for dev portal start page

---

qdrant-landing/content/articles/qa-with-cohere-and-qdrant.md
qdrant-landing/content/documentation/cloud/authentication.md
qdrant-landing/content/documentation/cloud/quickstart-cloud.md

This PR removes all the references to staging-cloud.qdrant.io

Remove all references to staging-cloud.qdrant.io

---

qdrant-landing/content/documentation/concepts/search.md

Refactors almost all of the **Recommend API** section, while adding the new `best_score` recommend strategy

Add recommendation strategies

---

qdrant-landing/content/documentation/guides/configuration.md

Similar to <https://github.com/qdrant/landing_page/pull/283>.
Update the configuration to our latest release.

Update configuration to v1.6.0

---

qdrant-landing/content/articles/fastembed.md

I marked all the code snippets as `python`, so the code colouring works.

Enable code colouring

---

qdrant-landing/content/documentation/integrations/mindsdb.md

Adds MindsDB to the list of supported integrations with usage info.

docs: Add MindsDB integration section

---

qdrant-landing/themes/qdrant/layouts/partials/footer.html

Got rid of repeating icons in the footer

---

qdrant-landing/content/documentation/integrations/autogen.md

Adds Autogen to the list of supported integrations with usage info.

docs: Add Autogen integration section

---

qdrant-landing/content/documentation/faq/database-optimization.md
qdrant-landing/content/documentation/faq/qdrant-fundamentals.md

Minor improvements on <https://github.com/qdrant/landing_page/pull/317>.

Minor FAQ improvements: spelling & formatting

---

qdrant-landing/content/documentation/faq/database-optimization.md
qdrant-landing/content/documentation/faq/qdrant-fundamentals.md
qdrant-landing/content/documentation/quick-start.md

I added a TypeScript implementation of the Quickstart, reproducing the same steps as Python version.

Add TypeScript version of Quickstart

---

qdrant-landing/content/documentation/cloud/authentication.md
qdrant-landing/content/documentation/cloud/quickstart-cloud.md
qdrant-landing/content/documentation/faq/database-optimization.md
qdrant-landing/content/documentation/faq/qdrant-fundamentals.md

This PR adds TypeScript examples to the Documentation / Cloud section

Add TypeScript examples for Documentation / Cloud

---

qdrant-landing/config.toml
qdrant-landing/content/documentation/cloud/authentication.md
qdrant-landing/content/documentation/cloud/quickstart-cloud.md
qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/filtering.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/payload.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/search.md
qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/concepts/storage.md
qdrant-landing/content/documentation/faq/database-optimization.md
qdrant-landing/content/documentation/faq/qdrant-fundamentals.md
qdrant-landing/content/documentation/guides/administration.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/multiple-partitions.md
qdrant-landing/content/documentation/guides/optimize.md
qdrant-landing/content/documentation/guides/quantization.md
qdrant-landing/content/documentation/guides/security.md
qdrant-landing/content/documentation/quick-start.md
qdrant-landing/content/documentation/tutorials/aleph-alpha-search.md
qdrant-landing/content/documentation/tutorials/async-api.md
qdrant-landing/content/documentation/tutorials/bulk-upload.md
qdrant-landing/content/documentation/tutorials/create-snapshot.md
qdrant-landing/content/documentation/tutorials/neural-search-fastembed.md
qdrant-landing/content/documentation/tutorials/neural-search.md
qdrant-landing/content/documentation/tutorials/search-beginners.md

This PR introduces the TypeScript versions of all the Python snippets presented in Documentation / Concepts, Guides, Cloud and Quickstart.

Add TypeScript examples for Documentation & Quickstart

---

qdrant-landing/content/articles/neural-search-tutorial.md
qdrant-landing/content/articles/seed-round.md
qdrant-landing/content/documentation/integrations/autogen.md

Resolves #366.
Resolves #377.
Resolves #391.

fix: broken external links

---

qdrant-landing/content/documentation/cloud/authentication.md

The feature has been rolled out to all regions.
Issue: https://github.com/qdrant/cloud-pm/issues/125

Document usage of Authorization header for authentication

---

qdrant-landing/content/articles/dedicated-service.md

The fourth table of contents link was incorrect. This PR fixes that.

Fix fourth ToC link not working

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/search.md

This PR adds documentation for sparse vectors.
I am a bit unsure about adding a dedicated concept page because it is a crosscutting aspect through collections, search, update.

Sparse vectors documentation

---

qdrant-landing/content/articles/qa-with-cohere-and-qdrant.md
qdrant-landing/content/documentation/embeddings/aleph-alpha.md
qdrant-landing/content/documentation/embeddings/cohere.md
qdrant-landing/content/documentation/embeddings/jina-embeddings.md
qdrant-landing/content/documentation/embeddings/openai.md
qdrant-landing/content/documentation/frameworks/airbyte.md
qdrant-landing/content/documentation/frameworks/autogen.md
qdrant-landing/content/documentation/frameworks/cheshire-cat.md
qdrant-landing/content/documentation/frameworks/dlt.md
qdrant-landing/content/documentation/frameworks/docarray.md
qdrant-landing/content/documentation/frameworks/dspy.md
qdrant-landing/content/documentation/frameworks/fifty-one.md
qdrant-landing/content/documentation/frameworks/fondant.md
qdrant-landing/content/documentation/frameworks/haystack.md
qdrant-landing/content/documentation/frameworks/langchain.md
qdrant-landing/content/documentation/frameworks/llama-index.md
qdrant-landing/content/documentation/frameworks/mindsdb.md
qdrant-landing/content/documentation/frameworks/privategpt.md
qdrant-landing/content/documentation/frameworks/spark.md
qdrant-landing/content/documentation/frameworks/txtai.md

Resolves #474.
Resolves #473.
Resolves #472.
Resolves #471.
Resolves #470.
Resolves #413.
Resolves #427.
Resolves #436.
Resolves #456.

fix: broken links, images

---

qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/multiple-partitions.md
qdrant-landing/content/documentation/guides/optimize.md
qdrant-landing/content/documentation/guides/quantization.md

This PR
- Adds the Java client usage to the https://qdrant.tech/documentation/guides section.

docs: Java client usage for guides

---

qdrant-landing/content/documentation/frameworks/fondant.md

The Fondant documentation is outdated. We have release a new version of Fondant including an updated pipeline interface. This PR updates the documentation accordingly.

Update Fondant documentation

---

qdrant-landing/content/documentation/guides/configuration.md
qdrant-landing/content/documentation/guides/installation.md
qdrant-landing/content/documentation/interfaces.md

* Add a section about requirements for Qdrant
* Separate installation instructions between recommended installations for prod and dev
* Add cloud option
* Add enterprise operator option
* Add details about configuring the database with docker

Improve installation docs

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/points.md

This PR updates the Java client usage according to the [`v1.7.1`](https://github.com/qdrant/java-client/releases/tag/v1.7.1) release.

docs: Update Java client usage 1.7.1

---

qdrant-landing/content/blog/qdrant-n8n.md
qdrant-landing/content/blog/qdrant-supports-arm-architecture.md
qdrant-landing/content/blog/qdrant-unstructured.md

Updates the blog preview images for `blog/qdrant-n8n.md` and `blog/qdrant-unstructured.md`.

docs: update blog previews

---

qdrant-landing/content/blog/qdrant-cloud-on-microsoft-azure.md

Will revert after building and confirming

Test to confirm publication on a specific date

---

qdrant-landing/content/blog/qdrant-cloud-on-microsoft-azure.md

Had to be absolutely sure about the URL

Revert date test, #533

---

qdrant-landing/content/documentation/guides/installation.md

Also need to check the logs for the committing PR, why didn't lychee (the link checker) catch it?

Installation Guide page: fix broken link

---

README.md
qdrant-landing/themes/qdrant/archetypes/blog-post.md

Based on the blog posts that I've reviewed so far, I'm guessing that a few of us don't (yet) understand the process for creating a blog post. I'm hoping this clarifies things.
(I'll also find someplace to doc this in Notion.)

Update blog post directions

---

qdrant-landing/content/articles/discovery-search.md

For some reason the article hasn't been published yet, I'm hoping this fixes it

Publish discovery article

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/points.md

Replaces https://github.com/qdrant/landing_page/pull/561
Link to build page:
https://deploy-preview-565--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/collections/

Add curl commands to collections page

---

qdrant-landing/content/documentation/cloud/capacity-sizing.md

Fixes <https://github.com/qdrant/landing_page/issues/591>

Fix typo on cloud capacity and sizing page

---

qdrant-landing/content/documentation/cloud/gcp-marketplace.md

I've made this parallel to https://qdrant.tech/documentation/cloud/aws-marketplace/, with minor changes to more closely follow the Google Developer style guide.
Build preview: https://deploy-preview-574--condescending-goldwasser-91acf0.netlify.app/documentation/cloud/gcp-marketplace/
Closely related: https://github.com/qdrant/landing_page/pull/569

Add GCP marketplace instructions

---

qdrant-landing/content/documentation/embeddings/openai.md

OpenAI SDK has changed the API spec. This PR adapts our example to the new interface.
See: https://github.com/openai/openai-python/discussions/742

Fix the OpenAI example to use the new API

---

qdrant-landing/content/documentation/concepts/collections.md

- make HTTP example first, as bash is too verbose and can't be used by everyone
- Fix wrong collection info request

fix bash examples

---

qdrant-landing/content/articles/multitenancy.md

The multitenancy article needs to be displayed as the first one on the list. This PR pushes it to the top.

Push multitenancy to top

---

qdrant-landing/content/documentation/embeddings/nomic.md

This PR clarifies it is required to have a Nomic token configured.

Add info about Nomic API token

---

qdrant-landing/content/documentation/cloud/authentication.md
qdrant-landing/content/documentation/cloud/quickstart-cloud.md
qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/explore.md
qdrant-landing/content/documentation/concepts/filtering.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/payload.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/search.md
qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/concepts/storage.md
qdrant-landing/content/documentation/quick-start.md

This PR adds the C# client usage to the quick-start and concepts sections of the documentation.
[Preview](https://deploy-preview-599--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/)

docs: C# client usage

---

qdrant-landing/content/documentation/concepts/filtering.md

This fixes the nested filter example. The JSON blob is currently incorrect.
cc @kaancfidan

Fix JSON in nested filter example

---

qdrant-landing/content/documentation/interfaces.md
qdrant-landing/content/documentation/web-ui.md

I think this took me < 1h to set up, and addresses IMO one of the biggest misses in our docs.

Set up separate Web UI doc

---

qdrant-landing/content/documentation/web-ui.md

Essentially correcting a typo, so I'm merging on my own authority.

Remove confusing line from Web UI page

---

qdrant-landing/content/articles/sparse-vectors.md

The revised link has the new Qdrant API, the previous notebook was based on the dev branch and was broken

Update Colab link in sparse-vectors.md

---

qdrant-landing/content/documentation/cloud/_index.md
qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/embeddings/jina-embeddings.md
qdrant-landing/content/documentation/frameworks/haystack.md
qdrant-landing/content/documentation/frameworks/langchain.md
qdrant-landing/content/documentation/frameworks/llama-index.md
qdrant-landing/content/documentation/guides/common-errors.md
qdrant-landing/content/documentation/guides/configuration.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/multiple-partitions.md
qdrant-landing/content/documentation/guides/quantization.md
qdrant-landing/content/documentation/interfaces.md
qdrant-landing/content/documentation/overview/qdrant-alternatives.md

Added aliases to the documentation pages that will redirect outdated links to their new locations.

Added redirects

---

qdrant-landing/content/documentation/embeddings/gemini.md

Companion notebook is here: https://github.com/qdrant/examples/pull/35

Update Gemini embedding code and Qdrant indexing

---

qdrant-landing/content/documentation/embeddings/openai.md

[Preview](https://deploy-preview-693--condescending-goldwasser-91acf0.netlify.app/documentation/embeddings/openai/)

docs: OpenAI update

---

qdrant-landing/content/articles/templates/release-post-template.md

Starting point for future release posts

Set up release post template

---

qdrant-landing/content/documentation/embeddings/mistral.md

Follow-up to https://github.com/qdrant/landing_page/pull/691#discussion_r1516344098 
As suggested by @joein . However, he's on PTO, so I'll submit to @NirantK for his OK.
Build of section with proposed table update: https://deploy-preview-699--condescending-goldwasser-91acf0.netlify.app/documentation/embeddings/mistral/#using-mistral-embedding-models-with-binary-quantization

Update Mistral table for clarity

---

qdrant-landing/content/documentation/embeddings/gemini.md

Similar to #699 
[Here's the build](https://deploy-preview-704--condescending-goldwasser-91acf0.netlify.app/documentation/embeddings/gemini/#using-gemini-embedding-models-with-binary-quantization). Scroll down a bit for the updated table.

Update Gemini table for clarity

---

qdrant-landing/content/documentation/faq/qdrant-fundamentals.md

This commit permit to tell our users that we don't support downgrading of clusters

docs(faq): add downgrade question

---

qdrant-landing/content/documentation/cloud/create-cluster.md

Fix typos in cluster page

---

qdrant-landing/content/documentation/concepts/collections.md

Fix misplaced cshard example

---

qdrant-landing/content/documentation/cloud/capacity-sizing.md

We need doc as a link from the cluster part of our UI, for more info on why to increase disk space

Support info from UI for disk space considerations

---

qdrant-landing/content/documentation/frameworks/llama-index.md
qdrant-landing/content/documentation/tutorials/llama-index-multitenancy.md

This PR updates our Llama Index examples to work with Llama Index 0.10.

Update Llama Index usage examples to work with 0.10

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

This just keeps the ordering guarantees for each shard transfer method.
The consistency guarantees that were listed before may give a false sense of integrity, that's why I've removed them.
Rendered: https://deploy-preview-741--condescending-goldwasser-91acf0.netlify.app/documentation/guides/distributed_deployment/#shard-transfer-method

For shard transfer methods, don't list consistency but ordering guarantees

---

qdrant-landing/content/documentation/concepts/indexing.md

[Section preview](https://deploy-preview-737--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/indexing/#parameterized-index)

docs: Parameterized int index Java, C# examples

---

qdrant-landing/content/docker-deploy/_index.md
qdrant-landing/themes/qdrant-2024/assets/css/_components.scss
qdrant-landing/themes/qdrant-2024/assets/css/components/_utilites.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_docker-deploy.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/docker-deploy.html

In this PR:
- line numbers excluded from text select
- removed position absolute from code tag to make selecting of text more comfortable

Updated styles for docker commands to make copying more user-friendly

---

qdrant-landing/content/documentation/concepts/payload.md

We forgot to document this new feature.
https://github.com/qdrant/landing_page/issues/742

Document nested payload modification

---

qdrant-landing/content/documentation/guides/monitoring.md

Had a customer ask about monitoring their Qdrant Cloud instance and so I expanded the docs to cover the items that customer needed.

Elaborator on monitoring, especially for cloud

---

qdrant-landing/content/documentation/cloud/_index.md
qdrant-landing/content/documentation/hybrid-cloud/networking-logging-monitoring.md
qdrant-landing/content/documentation/hybrid-cloud/operator-configuration.md
qdrant-landing/content/documentation/hybrid-cloud/platform-deployment-options.md

∙ - Cleanup Managed Cloud main page
∙ - Adapt networkpolicies to new default
∙ - Cleanup operator configuration
∙ - Add platform specific docs

Adapt Hybrid Cloud docs

---

qdrant-landing/content/documentation/guides/installation.md
qdrant-landing/content/documentation/guides/security.md

This PR adds extra emphasis to the fact that just doing `docker run` or even `docker compose up` are not recommended for production due to the lack of default security settings.

Add container hardening advice

---

qdrant-landing/content/documentation/hybrid-cloud/platform-deployment-options.md

- Adjusted the Civo section position to maintain alphabetical ordering.
- Some miscellaneous rephrasing.

docs: Sort platform-deployment-options.md

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

Add an explicit warning about large cardinalities in user defined sharding.

Add warning for user defined sharding

---

qdrant-landing/content/documentation/examples/_index.md
qdrant-landing/content/documentation/examples/databricks.md

docs: Dict options databricks.md

---

qdrant-landing/content/documentation/concepts/collections.md

Documents: <https://github.com/qdrant/qdrant/pull/3962>
It describes the grey collection status, and what users can do to resolve that status.
Rendered: <https://deploy-preview-779--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/collections/#collection-info>

Document grey collection status for Qdrant 1.9

---

qdrant-landing/content/documentation/concepts/collections.md

ToDo: requires examples in other SDKs

add description of vector datatypes for v1.9.0 release

---

qdrant-landing/content/headless/footer.md
qdrant-landing/content/headless/get-started-blogs.md
qdrant-landing/content/headless/get-started-small-database.md
qdrant-landing/content/headless/get-started-small-rocket.md
qdrant-landing/content/headless/get-started.md
qdrant-landing/content/headless/menu.md
qdrant-landing/content/headless/newsletter.md
qdrant-landing/layouts/partials/README.md
qdrant-landing/layouts/partials/preview-image.html
qdrant-landing/themes/qdrant-2024/assets/css/_components.scss
qdrant-landing/themes/qdrant-2024/assets/css/components/_input.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hubspot-form.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_newsletter.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-blog-features.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-blog-hero.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_subscribe-form.scss
qdrant-landing/themes/qdrant-2024/assets/css/search/search.scss
qdrant-landing/themes/qdrant-2024/assets/js/search/search.js
qdrant-landing/themes/qdrant-2024/layouts/partials/css.html
qdrant-landing/themes/qdrant-2024/layouts/partials/footer.html
qdrant-landing/themes/qdrant-2024/layouts/partials/get-started-small.html
qdrant-landing/themes/qdrant-2024/layouts/partials/get-started.html
qdrant-landing/themes/qdrant-2024/layouts/partials/js.html
qdrant-landing/themes/qdrant-2024/layouts/partials/newsletter.html
qdrant-landing/themes/qdrant-2024/layouts/partials/pagination.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-articles-posts.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-blog-features.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-blog-hero.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-blog-posts.html

- added link to posts
- other missing links
- subscribe Hubspot form
- page-search plugin (require re-indexing, because the HTML structure changed and plugin gets wrong selector from the backend)

Article and blog pages update

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/explore.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/guides/distributed_deployment.md

[PREVIEW](https://deploy-preview-868--condescending-goldwasser-91acf0.netlify.app/documentation)

docs: Fixed SDK snippets

---

qdrant-landing/themes/qdrant-2024/assets/css/_bootstrap-custom.scss
qdrant-landing/themes/qdrant-2024/assets/css/_components.scss
qdrant-landing/themes/qdrant-2024/assets/css/components/_alerts.scss
qdrant-landing/themes/qdrant-2024/assets/css/mixins/_mixins.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_documentation-article.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-post.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/documentation-article.html

Added small fixes to docs page

Docs update

---

qdrant-landing/themes/qdrant-2024/assets/css/partials/_advanced-search-use-cases.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_docker-deploy.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_documentation-article.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_footer.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hybrid-cloud-cases.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hybrid-cloud-features.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hybrid-cloud-hero.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hybrid-cloud-how-it-works.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hybrid-cloud-kubernetes-clusters.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_menu-mobile.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-articles-hero.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-articles-posts.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-blog-features.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-blog-posts.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-post.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_tutorials.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_use-cases-vector-features.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/advanced-search-features.html
qdrant-landing/themes/qdrant-2024/layouts/partials/advanced-search-use-cases.html
qdrant-landing/themes/qdrant-2024/layouts/partials/docker-deploy.html
qdrant-landing/themes/qdrant-2024/layouts/partials/hybrid-cloud-features.html
qdrant-landing/themes/qdrant-2024/layouts/partials/hybrid-cloud-hero.html
qdrant-landing/themes/qdrant-2024/layouts/partials/hybrid-cloud-how-it-works.html
qdrant-landing/themes/qdrant-2024/layouts/partials/hybrid-cloud-kubernetes-clusters.html
qdrant-landing/themes/qdrant-2024/layouts/partials/menu-mobile.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-articles-posts.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-blog-features.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-blog-hero.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-blog-posts.html
qdrant-landing/themes/qdrant-2024/layouts/partials/tutorials.html

Moved change to mobile design from `xl` to `lg` on some pages:
- hybrid cloud
- advanced search
- blog
- article

Overall fixes

---

qdrant-landing/content/qdrant-cloud/qdrant-cloud-hero.md
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hero.scss
qdrant-landing/themes/qdrant-2024/assets/js/helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/assets/js/scroll-handler.js
qdrant-landing/themes/qdrant-2024/layouts/advanced-search/list.html
qdrant-landing/themes/qdrant-2024/layouts/data-analysis/list.html
qdrant-landing/themes/qdrant-2024/layouts/partials/footer.html
qdrant-landing/themes/qdrant-2024/layouts/partials/js.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-cloud-hero.html
qdrant-landing/themes/qdrant-2024/layouts/recommendations/list.html
qdrant-landing/themes/qdrant-2024/layouts/retrieval-augmented-generation/list.html

Hid the video on the cloud page and run format

Hid the video on the cloud page

---

qdrant-landing/content/documentation/concepts/collections.md

docs: Fix collection existence endpoint

---

qdrant-landing/themes/qdrant-2024/layouts/partials/js.html

feat: CMD + K to search - New Design

---

qdrant-landing/content/documentation/concepts/indexing.md

Re-writes the documentation about sparse vector index.

rewrite sparse index documentation

---

qdrant-landing/content/contact-hybrid-cloud/_index.md
qdrant-landing/content/enterprise-solutions/enterprise-solutions-hero.md
qdrant-landing/content/headless/get-contacted-with-question-sales.md
qdrant-landing/content/hybrid-cloud/get-contacted-with-question.md
qdrant-landing/content/hybrid-cloud/hybrid-cloud-hero.md
qdrant-landing/content/private-cloud/private-cloud-hero.md
qdrant-landing/themes/qdrant-2024/layouts/contact-hybrid-cloud/list.html
qdrant-landing/themes/qdrant-2024/layouts/contact-hybrid-cloud/single.html
qdrant-landing/themes/qdrant-2024/layouts/enterprise-solutions/list.html
qdrant-landing/themes/qdrant-2024/layouts/hybrid-cloud/list.html
qdrant-landing/themes/qdrant-2024/layouts/partials/contact-hero.html

- added a contact page for hybrid cloud
- changed "Contact us" links on enterprise solutions and private cloud pages

Contact page for hybrid cloud

---

qdrant-landing/content/pricing/qdrant-pricing-doors-b.md
qdrant-landing/themes/qdrant-2024/assets/css/base.scss
qdrant-landing/themes/qdrant-2024/assets/css/benchmarks.scss
qdrant-landing/themes/qdrant-2024/assets/css/mixins/_marketplaces.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hero.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hybrid-cloud-partners.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-pricing-doors-b.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_subscribe-form.scss
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/layouts/partials/benchmark_chart.html
qdrant-landing/themes/qdrant-2024/layouts/partials/benchmark_filter_chart.html
qdrant-landing/themes/qdrant-2024/layouts/partials/hybrid-cloud-partners.html
qdrant-landing/themes/qdrant-2024/layouts/partials/marketplaces.html
qdrant-landing/themes/qdrant-2024/layouts/partials/menu-mobile.html

Fixes:
- body's scroll over the mobile menu
- benchmarks plot labels
- pricing content
- marketplaces overlay
- hybrid cloud partners overlay
- email form error message

Some fixes for new site

---

qdrant-landing/content/articles/metric-learning-tips.md
qdrant-landing/content/documentation/api-reference.md
qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/explore.md
qdrant-landing/content/documentation/concepts/payload.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/search.md
qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/telemetry.md
qdrant-landing/content/documentation/interfaces/_index.md
qdrant-landing/content/features/easy-to-use.md

docs: Switch over API reference to api.qdrant.tech

---

qdrant-landing/content/documentation/concepts/indexing.md

docs: Nested indexing clarification

---

qdrant-landing/content/documentation/examples/rag-chatbot-scaleway.md

Use the set-up hybrid cluster instead in the tutorial.

docs: Fixed instantiation rag-chatbot-scaleway.md

---

qdrant-landing/content/documentation/concepts/filtering.md

docs: Fixed nested filtering snippet filtering.md

---

qdrant-landing/content/documentation/tutorials/hybrid-search-fastembed.md

Example code was not working. Error corrected.

Corrected example code in hybrid-search-fastembed.md

---

qdrant-landing/content/headless/footer.md

Added https://status.qdrant.io/ to Footer under Developer Section.

Adding Stauts Page to Footer

---

qdrant-landing/themes/qdrant-2024/assets/css/components/_lang-switcher.scss

Snippet tabs height fix

---

qdrant-landing/content/articles/bm42.md

There are quite a bit of grammar fixes, but I kept the meaning intact. 
Nothing changed from the code/story/explanations.
Check the conclusion, that's where I wrote the most changes.

ARTICLE: BM42: Proofreading & Editing 

---

qdrant-landing/content/documentation/concepts/indexing.md

SECTION PREVIEW: https://deploy-preview-996--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/indexing/#idf-modifier

Qdrant 1.10: describe IDF computation

---

qdrant-landing/themes/qdrant-2024/layouts/partials/head.html

Potentially afffects other pages

Re-add missing JS to fix benchmarks

---

qdrant-landing/content/headless/footer.md

changed footer title from Community to Discord for easy discovery

update footer link for discord

---

qdrant-landing/content/blog/qdrant-1.10.x.md
qdrant-landing/content/documentation/concepts/hybrid-queries.md

Reported by a user on Discord.

Fix query JSON example

---

qdrant-landing/content/documentation/hybrid-cloud/hybrid-cloud-setup.md

This clarifies prerequisites and adds information about the new config UI

Small improvements for the Hybrid Cloud docs

---

qdrant-landing/content/blog/qdrant-1.10.x.md

docs: Added TS, Py snippets to 1.10 blog and Markdown formatting

---

qdrant-landing/content/documentation/frameworks/langchain.md

Describes the new class and searching mechanisms.

docs: Updated Langchain docs

---

qdrant-landing/content/documentation/examples/databricks.md
qdrant-landing/content/documentation/examples/qdrant-airflow-astronomer.md
qdrant-landing/content/documentation/faq/qdrant-fundamentals.md
qdrant-landing/content/documentation/frameworks/nifi.md

docs: Updated FAQ and Query API usage

---

qdrant-landing/content/articles/discovery-search.md

Fixes for https://github.com/qdrant/landing_page/pull/908#pullrequestreview-2175703075

Proofread Discovery article

---

qdrant-landing/content/documentation/overview/vector-search.md

Add Vector Search Video to Doc

---

qdrant-landing/content/documentation/guides/configuration.md

See also https://qdrant.tech/articles/io_uring/#and-what-about-qdrant

Add documentation for config value storage.async_scorer

---

qdrant-landing/content/documentation/overview/_index.md

> where each element of the vector corresponds to a specific feature or attribute of the object
_that's not true for embeddings_
> distances
_made it a lil bit more technical_

Fixed the incorrect explanation of vectors & their similarity metrics

---

qdrant-landing/content/documentation/_index.md

Link to Qdrant Demo on Homepage

---

qdrant-landing/content/documentation/guides/security.md

This section wasn't updated when adding the docs for the Query API

Add `query_points` to the access table

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/explore.md
qdrant-landing/content/documentation/concepts/filtering.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/payload.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/search.md
qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/concepts/storage.md
qdrant-landing/content/documentation/concepts/vectors.md

docs: New Rust SDK snippets for /concepts

---

qdrant-landing/content/documentation/cloud/authentication.md
qdrant-landing/content/documentation/cloud/qdrant-cloud-setup.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/multiple-partitions.md
qdrant-landing/content/documentation/guides/optimize.md
qdrant-landing/content/documentation/guides/quantization.md
qdrant-landing/content/documentation/guides/security.md
qdrant-landing/content/documentation/quickstart.md

docs: New Rust SDK snippets for /quickstart, /guides and /cloud

---

qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/guides/configuration.md

Fixes https://github.com/qdrant/qdrant/issues/4701#issuecomment-2255084773

docs: Updated S3 snapshots config

---

qdrant-landing/content/documentation/frameworks/airflow.md
qdrant-landing/content/documentation/send-data/databricks.md
qdrant-landing/content/documentation/send-data/qdrant-airflow-astronomer.md

- As the title goes
- Also fixes some aliases as per their previous locations. There are broken links on Google.

docs: Add install instruction airflow.md

---

qdrant-landing/content/documentation/cloud/cluster-scaling.md

This specifically adds information on vertical downscaling.

Add more details on vertical and horizontal scaling in cloud

---

qdrant-landing/content/subscribe/_index.md
qdrant-landing/themes/qdrant-2024/assets/css/partials/_contact-form.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hubspot-form.scss

Styles for a Hubspot form checkbox, long legal consent, new title of the subscribe form

Form fixes

---

qdrant-landing/content/partners/partners-integrations.md
qdrant-landing/content/retrieval-augmented-generation/retrieval-augmented-generation-integrations.md

I am changing the company's name, as requested in the Slack conversation.
Preview: https://deploy-preview-1070--condescending-goldwasser-91acf0.netlify.app/rag/

Change the name of our company to "Jina AI" instead of "Jina"

---

qdrant-landing/content/documentation/frameworks/confluent.md

Updates as per the Confluent team's request.

docs: Confluent copy edits

---

qdrant-landing/content/headless/top-banner.md
qdrant-landing/static/admin/config.yml
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/layouts/partials/top-banner.html

This PR introduces the following functionality:
- Start and end dates can be added for displaying a banner on the site. 
- The banner can be edited in CMS

Added activity dates for the top banner and cms config

---

qdrant-landing/content/documentation/guides/installation.md

In guides, list installation first

---

qdrant-landing/content/articles/hybrid-search.md

Suggestions as per SEO agency. Nothing special, just the title and headings....few links here and there.

[SEO] Vector Search Revamped

---

qdrant-landing/content/pricing/_index.md
qdrant-landing/content/recommendations/_index.md

Fixed SEO terms for 
- pricing
- recommendations

[SEO] Title & Desc Fixes

---

qdrant-landing/content/advanced-search/_index.md

This PR fixes all the titles and descriptions as per JDM suggestions.

[SEO] Fix Titles and Descriptions

---

qdrant-landing/content/documentation/embeddings/_index.md
qdrant-landing/content/documentation/embeddings/azure.md
qdrant-landing/content/documentation/embeddings/clarifai.md
qdrant-landing/content/documentation/embeddings/clip.md
qdrant-landing/content/documentation/embeddings/cohere.md
qdrant-landing/content/documentation/embeddings/databricks.md
qdrant-landing/content/documentation/embeddings/gemini.md
qdrant-landing/content/documentation/embeddings/gpt4all.md
qdrant-landing/content/documentation/embeddings/gradientai.md
qdrant-landing/content/documentation/embeddings/instruct.md
qdrant-landing/content/documentation/embeddings/jina-embeddings.md
qdrant-landing/content/documentation/embeddings/johnsnow.md
qdrant-landing/content/documentation/embeddings/mistral.md
qdrant-landing/content/documentation/embeddings/mixedbread.md
qdrant-landing/content/documentation/embeddings/nomic.md
qdrant-landing/content/documentation/embeddings/nvidia.md
qdrant-landing/content/documentation/embeddings/oci.md
qdrant-landing/content/documentation/embeddings/ollama.md
qdrant-landing/content/documentation/embeddings/openai.md
qdrant-landing/content/documentation/embeddings/openclip.md
qdrant-landing/content/documentation/embeddings/premai.md
qdrant-landing/content/documentation/embeddings/snowflake.md
qdrant-landing/content/documentation/embeddings/together_ai.md
qdrant-landing/content/documentation/embeddings/togetherai.md
qdrant-landing/content/documentation/embeddings/upstage.md
qdrant-landing/content/documentation/embeddings/voyage.md
qdrant-landing/content/documentation/embeddings/watsonx.md

[PREVIEW](https://deploy-preview-1122--condescending-goldwasser-91acf0.netlify.app/documentation/embeddings/)

[Docs] Add Embedding Providers

---

qdrant-landing/content/documentation/data-management/fluvio.md

fixed: typo fluvio.md

---

qdrant-landing/content/documentation/embeddings/jina-embeddings.md

Update documentation of jina embeddings:
1. Created a detailed model list with tech summary.
2. add description of task adapters of `jina-embeddings-v3` and how to use them.
3. add short description of MRL performance to give user a hint how to balance between storage and performance.
4. updated code snnipt.

docs: update jina embeddings integration

---

qdrant-landing/content/documentation/concepts/points.md

doc: Added missed C#, Go snippet

---

qdrant-landing/content/documentation/infrastructure/pulumi.md
qdrant-landing/content/documentation/infrastructure/terraform.md

https://qdrant.tech/documentation/platforms/terraform/ will work.

docs: Route alias for Pulumi, Terraform

---

qdrant-landing/content/blog/qdrant-startup-program.md

docs: Update Airbyte perks for startups

---

qdrant-landing/content/documentation/concepts/payload.md

[Rendered](https://deploy-preview-1178--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/payload/#facet-counts)
Documents the new Facet API, to be introduced in v1.12.0

Facet docs

---

qdrant-landing/content/articles/what-is-a-vector-database.md

docs: Fixes for what-is-a-vector-database.md

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/sycamore.md

https://github.com/aryn-ai/sycamore/pull/821

docs: Sycamore Integration

---

qdrant-landing/content/pricing/qdrant-pricing-doors-b.md

Update pricing page to match terminology we use in user sales resources

---

qdrant-landing/content/documentation/concepts/explore.md
qdrant-landing/content/documentation/concepts/filtering.md
qdrant-landing/content/documentation/concepts/hybrid-queries.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/payload.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/vectors.md
qdrant-landing/content/documentation/guides/administration.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/optimize.md

I've compiled and checked the snippets. Except for the Python ones. cc @mrscoopers.

docs: Proofread and updated snippets

---

qdrant-landing/content/documentation/_index.md

Fixed dabatase to database

---

qdrant-landing/content/enterprise-solutions/enterprise-solutions-hero.md
qdrant-landing/content/headless/get-started.md
qdrant-landing/content/headless/main/hero.md
qdrant-landing/content/headless/menu.md
qdrant-landing/content/qdrant-cloud/qdrant-cloud-hero.md
qdrant-landing/content/qdrant-vector-database/qdrant-vector-database-hero.md
qdrant-landing/themes/qdrant-2024/layouts/hybrid-cloud/list.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-cloud-bento-cards.html
qdrant-landing/themes/qdrant-2024/layouts/qdrant-cloud/list.html

Replaced the CTA text and removed some blocks as required for [this task](https://www.notion.so/qdrant/Update-buttons-on-site-to-impact-conversions-for-sales-requests-new-accounts-created-121674779d3380fabdc0efc1de1a3b20).

Replaced CTA text and removed some blocks

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/explore.md
qdrant-landing/content/documentation/concepts/filtering.md
qdrant-landing/content/documentation/concepts/hybrid-queries.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/vectors.md
qdrant-landing/content/documentation/guides/configuration.md
qdrant-landing/content/documentation/observability/datadog.md

Same as #1243
@mrscoopers, I had some free time, so I took the liberty of proofreading the Python ones too.
Resolves https://www.notion.so/qdrant/32773315ad544158a1a222ef698dd228?v=06e3d5f5d3bd4d02bcfaa27cfd79a37a&p=11f674779d3380d38756e6504da1a5f4&pm=s

docs: Proofread Python snippets

---

qdrant-landing/config.toml
qdrant-landing/content/documentation/tutorials/multimodal-search-fastembed.md
qdrant-landing/themes/qdrant-2024/assets/css/partials/_documentation.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_table-of-contents.scss
qdrant-landing/themes/qdrant-2024/assets/js/constants.js
qdrant-landing/themes/qdrant-2024/assets/js/documentation.js
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/assets/js/table-of-content.js
qdrant-landing/themes/qdrant-2024/assets/js/vendor/anchor.js
qdrant-landing/themes/qdrant-2024/layouts/partials/table-of-contents.html
qdrant-landing/themes/qdrant-2024/package.hugo.json
qdrant-landing/themes/qdrant-2024/package.json

Highlighting TOC links while scrolling + fix for content width

TOC scroll spy

---

qdrant-landing/content/documentation/embeddings/ollama.md

Resolves #1263
Resolves #1262
Resolves #1261

doc: Fix Ollama example

---

netlify.toml

New Business Tier Workspace in Segment that is EU based
- Simply swapping out old writeKeys for the new workspace

Update segmentWriteKeys for EU Workspace

---

qdrant-landing/themes/qdrant-2024/layouts/partials/js-head.html

simple cache bust for Segment Write Key
`?v=eu` moving from US to EU based Segment Workspace

Cache busting for new segment write key

---

qdrant-landing/themes/qdrant-2024/assets/css/main.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_qdrant-blog-post.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_table-of-contents.scss
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-post.html
qdrant-landing/themes/qdrant-2024/layouts/partials/table-of-contents.html

Reuse TOC from documentation on blog pages to:
- so that it has highlighting on hover and scrolling 
- avoid duplicating code

Reusing TOC from docs on blog pages

---

qdrant-landing/content/documentation/platforms/_index.md
qdrant-landing/content/documentation/platforms/kotaemon.md

docs: Kotaemon integration

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/ragbits.md

docs: RAGBits integration

---

qdrant-landing/content/headless/main/hero.md

Hero button text and link upd

---

qdrant-landing/content/documentation/private-cloud/configuration.md

"Privagte" typo

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/swarm.md

docs: Swarm integration example

---

qdrant-landing/content/advanced-search/advanced-search-features.md
qdrant-landing/content/advanced-search/advanced-search-use-cases.md
qdrant-landing/content/documentation/advanced-tutorials/_index.md
qdrant-landing/content/documentation/advanced-tutorials/code-search.md
qdrant-landing/content/documentation/advanced-tutorials/collaborative-filtering.md
qdrant-landing/content/documentation/advanced-tutorials/multimodal-search-fastembed.md
qdrant-landing/content/documentation/beginner-tutorials/_index.md
qdrant-landing/content/documentation/beginner-tutorials/hybrid-search-fastembed.md
qdrant-landing/content/documentation/beginner-tutorials/neural-search.md
qdrant-landing/content/documentation/beginner-tutorials/retrieval-quality.md
qdrant-landing/content/documentation/beginner-tutorials/search-beginners.md
qdrant-landing/content/documentation/build-tab.md
qdrant-landing/content/documentation/database-tutorials/_index.md
qdrant-landing/content/documentation/database-tutorials/async-api.md
qdrant-landing/content/documentation/database-tutorials/bulk-upload.md
qdrant-landing/content/documentation/database-tutorials/create-snapshot.md
qdrant-landing/content/documentation/database-tutorials/huggingface-datasets.md
qdrant-landing/content/documentation/dl-tutorials.md

[devportal] Create a Separate Tutorials Section

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/crewai.md

docs: CrewAI integration example

---

qdrant-landing/content/documentation/embeddings/jina-embeddings.md

They gave me examples, I skimmed through

For jina clip v2 release tmrw

---

qdrant-landing/content/documentation/embeddings/jina-embeddings.md
qdrant-landing/content/documentation/interfaces.md

docs: Misc. fixes jina-embeddings.md

---

qdrant-landing/content/documentation/concepts/vectors.md

docs: dense+sparse upload code snippets

---

qdrant-landing/content/documentation/concepts/payload.md

Got stuck myself with Python client until figured out why it returned me less values than I had in the collection
Decided to add this note

Little addition to docs

---

qdrant-landing/content/documentation/embeddings/_index.md
qdrant-landing/content/documentation/embeddings/aleph-alpha.md
qdrant-landing/content/documentation/embeddings/bedrock.md
qdrant-landing/content/documentation/embeddings/cohere.md
qdrant-landing/content/documentation/embeddings/gemini.md
qdrant-landing/content/documentation/embeddings/jina-embeddings.md
qdrant-landing/content/documentation/embeddings/mistral.md
qdrant-landing/content/documentation/embeddings/mixedbread.md
qdrant-landing/content/documentation/embeddings/mixpeek.md
qdrant-landing/content/documentation/embeddings/nomic.md
qdrant-landing/content/documentation/embeddings/nvidia.md
qdrant-landing/content/documentation/embeddings/ollama.md
qdrant-landing/content/documentation/embeddings/openai.md
qdrant-landing/content/documentation/embeddings/premai.md
qdrant-landing/content/documentation/embeddings/snowflake.md
qdrant-landing/content/documentation/embeddings/twelvelabs.md
qdrant-landing/content/documentation/embeddings/upstage.md
qdrant-landing/content/documentation/embeddings/voyage.md

docs: Twelve Labs example

---

qdrant-landing/content/documentation/database-tutorials/automate-filtering-with-llms.md

This PR adds a tutorial about extracting the filters from text queries using LLMs (specifically Anthropic Claude, but the approach should be portable to different models).

Tutorial: automated filtering with LLMs

---

qdrant-landing/content/documentation/guides/monitoring.md

chore: fixed typos /guides/monitoring.md

---

qdrant-landing/content/documentation/cloud/cluster-scaling.md
qdrant-landing/content/documentation/cloud/create-cluster.md
qdrant-landing/content/documentation/hybrid-cloud/hybrid-cloud-cluster-creation.md
qdrant-landing/content/documentation/private-cloud/qdrant-cluster-management.md

* Add security notes
* Clarify horizontal scaling
* Document how to delete clusters

Cloud docs improvements

---

qdrant-landing/content/documentation/cloud/cluster-monitoring.md
qdrant-landing/content/documentation/guides/monitoring.md

Added info about new external monitoring endpoint and metrics

Add external monitoring docs

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/smolagents.md

docs: SmolAgents - Qdrant example

---

qdrant-landing/content/documentation/embeddings/twelvelabs.md

docs: Updated TwelveLabs embeddings

---

qdrant-landing/content/documentation/multimodal-search.md

I'll merge since its a  minor change.

docs: fix links multimodal-search.md

---

qdrant-landing/content/stars/stars-list.md

Hi guys, 
Since this month I work in a new company.
I changed my job position and description in stars list.
Thanks in advance

[stars_list] updated my job position

---

qdrant-landing/content/documentation/concepts/collections.md

[Rendered](https://deploy-preview-1393--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/collections/#strict-mode)
Document new `strict_mode_config` released in v1.13.0.

[docs] Docs for strict mode

---

qdrant-landing/content/blog/static-embeddings.md

Fix typo in static embeddings blog post

---

qdrant-landing/content/documentation/quickstart.md

Fixes <https://github.com/qdrant/landing_page/issues/1403>

Quote the path in docker run command

---

qdrant-landing/config.toml
qdrant-landing/themes/qdrant-2024/layouts/partials/js-head.html

Marketers now connect GTM and GA via Segment, so we no longer need a GTM script on the site. 
Don't merge without notifying @Alyonkka, she will check if everything works as expected.

Removing GTM and GA script, they are to be used trough the Segment now

---

qdrant-landing/content/documentation/guides/running-with-GPU.md

[Rendered](https://deploy-preview-1416--condescending-goldwasser-91acf0.netlify.app/documentation/guides/running-with-gpu/)
Main changes:
- link to NVIDIA/AMD sections, link to collection update API
- Use consistent spelling
- Fix typo

Minor GPU documentation tweaks

---

qdrant-landing/content/documentation/guides/running-with-GPU.md

[Rendered](https://deploy-preview-1417--condescending-goldwasser-91acf0.netlify.app/documentation/guides/running-with-gpu/)
I was a bit too quick with <https://github.com/qdrant/landing_page/pull/1416>. Two more tweaks :smiley:

Minor GPU documentation tweaks (2)

---

netlify.toml
qdrant-landing/config.toml
qdrant-landing/themes/qdrant-2024/assets/js/segment-helpers.js

- using our new Custom Domain with DNS Delegation setup for Segment
- update writeKey for Segment in staging as well with our new EU based Segment workspace

Update Segment for 1st party cookies

---

qdrant-landing/content/documentation/cloud/authentication.md

If you don't like it as a separate paragraph, I can merge it into the 2nd one.

Add minimum version for using JWT in cloud

---

qdrant-landing/content/documentation/cloud/backups.md

Relates to https://github.com/qdrant/cloud-pm/issues/2089

Update backups doc for Azure

---

qdrant-landing/content/documentation/frameworks/cheshire-cat.md

Hi, I update the Cheshire Cat project page adding two new links.

added new links in Cheshire Cat project page

---

qdrant-landing/content/documentation/hybrid-cloud/hybrid-cloud-cluster-creation.md

[PREVIEW](https://deploy-preview-1432--condescending-goldwasser-91acf0.netlify.app/documentation/hybrid-cloud/hybrid-cloud-cluster-creation/#watch-the-video)

[docs] Hybrid Cloud Authentication Video

---

qdrant-landing/content/documentation/guides/configuration.md

Added in 1.12.6: https://github.com/qdrant/qdrant/pull/5602

Add docs for the logger.format configuration field

---

qdrant-landing/content/documentation/private-cloud/qdrant-cluster-management.md

Part of https://github.com/qdrant/cloud-pm/issues/2367

Document P2P TLS support for private cloud

---

qdrant-landing/content/documentation/data-management/spark.md

Updates the Spark connector doc as per the new README at https://github.com/qdrant/qdrant-spark.
I'll merge since minor.

docs: Spark connector doc update

---

qdrant-landing/content/documentation/cloud/authentication.md
qdrant-landing/content/documentation/cloud/cluster-monitoring.md
qdrant-landing/content/documentation/cloud/qdrant-cloud-setup.md

* SSO
* External monitoring
* DB API keys with RBAC

Add new feature cloud videos to docs

---

qdrant-landing/content/blog/enterprise-vector-search.md

Ignore/close if this was intentional

Fix Grafana dashboard link in enterprise blog

---

qdrant-landing/themes/qdrant-2024/layouts/partials/js.html

Added the script provided by the marketing team. I have not removed the console log now, but I would like to do that later once we confirm the script is functioning properly and no further debugging is required.

Added HubSpot script to add values to hidden fields

---

netlify.toml
qdrant-landing/themes/qdrant-2024/layouts/get_anonymous_id/baseof.html

allow `<iframe>` embed on https://qdrant.io https://staging-cloud.qdrant.io for path `/get_anonymous_id`

Headers for get anonymous id

---

qdrant-landing/content/documentation/hybrid-cloud/hybrid-cloud-setup.md

https://github.com/qdrant/cloud-pm/issues/2782

Add warning for running hybrid cloud cleanup

---

qdrant-landing/content/documentation/private-cloud/api-reference.md
qdrant-landing/content/documentation/private-cloud/changelog.md
qdrant-landing/content/documentation/private-cloud/configuration.md
qdrant-landing/content/documentation/private-cloud/private-cloud-setup.md
qdrant-landing/content/documentation/private-cloud/qdrant-cluster-management.md

- **Qdrant private cloud 1.6.0**
- **Update for 1.6.1 and add GPU tutorial**

Private Cloud 1.6.1

---

qdrant-landing/content/documentation/cloud-rbac/permission-reference.md
qdrant-landing/package-lock.json

Ref: https://github.com/qdrant/cloud-pm/issues/2872
Merge after: https://github.com/qdrant/qdrant-cloud-ui/pull/1686
May need copy improvements:

RBAC permissions: auto-tick read checkboxes in permissions when write is ticket

---

qdrant-landing/content/documentation/database-tutorials/large-scale-search.md

[large-scale-search] add million unit

---

qdrant-landing/content/documentation/private-cloud/changelog.md
qdrant-landing/content/documentation/private-cloud/private-cloud-setup.md

https://github.com/qdrant/cloud-pm/issues/2985

Update private cloud to 1.6.3

---

qdrant-landing/content/documentation/database-tutorials/bulk-upload.md

Added recommendation for `m = 0` during ingestion and clarified risks of `indexing_threshold = 0`

[Docs] Updating recommendations for bulk upload

---

qdrant-landing/content/headless/footer.md
qdrant-landing/content/headless/menu.md
qdrant-landing/themes/qdrant-2024/assets/css/partials/_footer.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/footer.html

@generall you wanted to change some naming here

updated some items in navigations

---

qdrant-landing/content/blog/enterprise-vector-search.md

Blog-removed-waitlist

---

qdrant-landing/content/documentation/agentic-rag-camelai-discord.md
qdrant-landing/content/documentation/agentic-rag-crewai-zoom.md
qdrant-landing/content/documentation/agentic-rag-langgraph.md
qdrant-landing/content/documentation/data-ingestion-beginners.md
qdrant-landing/content/documentation/dl-ecosystem.md
qdrant-landing/content/documentation/fastembed/_index.md
qdrant-landing/content/documentation/multimodal-search.md
qdrant-landing/content/documentation/qdrant-mcp-server.md
qdrant-landing/content/documentation/rag-deepseek.md

- moved FastEmbed docs
- linked to external MCP repo
- potentially consider adding the MCP docs to the site for SEO and accessibility
- more FE docs to add?

[docs] Ecosystem Section

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/deepeval.md

docs: DeepEval integration

---

qdrant-landing/themes/qdrant-2024/assets/css/base.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/hubspot-form.html

This will filter out some dumbest bots from our form submissions (maybe).

Added honeypot field to forms

---

qdrant-landing/content/documentation/concepts/hybrid-queries.md

To be included in 1.14 release.
Related PR: qdrant/qdrant#6357

Specify that offset is not propagated into prefetches

---

qdrant-landing/themes/qdrant-2024/assets/css/components/_card.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_additional-resources.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_advanced-search-use-cases.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_community-features.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_link.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_use-cases-vector-cases.scss
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/layouts/partials/additional-resources.html
qdrant-landing/themes/qdrant-2024/layouts/partials/advanced-search-features.html
qdrant-landing/themes/qdrant-2024/layouts/partials/advanced-search-use-cases.html
qdrant-landing/themes/qdrant-2024/layouts/partials/ai-agents-features.html
qdrant-landing/themes/qdrant-2024/layouts/partials/community-features.html
qdrant-landing/themes/qdrant-2024/layouts/partials/core-features.html
qdrant-landing/themes/qdrant-2024/layouts/partials/enterprise-solutions-use-cases.html
qdrant-landing/themes/qdrant-2024/layouts/partials/feature-overview.html
qdrant-landing/themes/qdrant-2024/layouts/partials/use-cases-cards.html

Link cards

---

qdrant-landing/content/documentation/frameworks/testcontainers.md

Add .NET to Testcontainers now that the [nuget package has been released](https://www.nuget.org/packages/Testcontainers.Qdrant)

Add .NET to Testcontainers

---

qdrant-landing/content/documentation/fastembed/fastembed-splade.md

refactor code a bit, use more recent fastembed

some polishing, use more recent fastembed

---

qdrant-landing/content/documentation/rag-deepseek.md

https://github.com/qdrant/examples/pull/69

update rag deepseek tutorial with local inference

---

qdrant-landing/content/documentation/beginner-tutorials/hybrid-search-fastembed.md

Qdrant-client v1.14 adds implicit local inference, methods `.add` and `.query` will become deprecated.
This PR is a draft which updates the related code snippets, however, the descriptions have also been updated, but should still be polished (I might need some help here).
Also, the data should be recomputed and links to it should be updated (this I'll do on my own)

Hybrid search local inference

---

qdrant-landing/content/documentation/private-cloud/changelog.md
qdrant-landing/content/documentation/private-cloud/private-cloud-setup.md

Private cloud: More details in changelog

---

qdrant-landing/content/articles/miniCOIL.md

Made changes to the wording in some of the sentences but kept the content the same.

Update wording miniCOIL.md

---

qdrant-landing/content/documentation/private-cloud/qdrant-cluster-management.md

Followup of https://github.com/qdrant/operator/pull/481

Document ephemeral snapshot volumes for private clouds

---

qdrant-landing/content/legal/privacy-policy.md

Exchanged a privacy policy to the new one

---

netlify.toml

add login for production and development to headers for get_anonymous_id

Update Get Anonymous ID path Headers

---

.github/workflows/internal-dead-links.yml
qdrant-landing/content/documentation/private-cloud/qdrant-cluster-management.md

This PR adds Keboola to the platform integrations section.
- Added Keboola.md with documentation about using Qdrant with Keboola
- Updated the platforms index page to include Keboola in the table of integrations

docs: add Keboola platform integration

---

qdrant-landing/package-lock.json
qdrant-landing/package.json
qdrant-landing/themes/qdrant-2024/assets/js/search/search.js
qdrant-landing/themes/qdrant-2024/package.hugo.json
qdrant-landing/themes/qdrant-2024/package.json

update search plugin and use partition meta tag to filter documentation sections

---

qdrant-landing/content/documentation/guides/administration.md

Fix example and clarify usage of `unindexed_filtering_retrieve`

Fix strict mode example

---

qdrant-landing/content/documentation/cloud-quickstart.md

Updating old video to newer video David filmed before he left Then I can archive the old video
Then we can re-film the video with the new UI
and I will archive this one

Docs-Update-cloud-quickstart.md

---

qdrant-landing/content/documentation/advanced-tutorials/reranking-hybrid-search.md

Disable indexing for the multivector

Update reranking tutorial

---

qdrant-landing/content/documentation/concepts/explore.md

The formula is different to what we initially released. This change reflects the change in docs

Update `best_score` formula

---

qdrant-landing/themes/qdrant-2024/assets/css/partials/_hubspot-form.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/hubspot-form.html

Revert checkbox

---

qdrant-landing/content/documentation/cloud-rbac/permission-reference.md

I still don't like the use of `remove` vs `delete` in many cases but this clears up the errors for now

Modify Cloud RBAC permissions descriptions

---

qdrant-landing/content/documentation/advanced-tutorials/using-multivector-representations.md

As requested on Slack, I'm changing the tutorial to suggest batching. We don't have much data, but it's generally a good practice.

Tutorial: using multivectors - set the batch size for points upload

---

qdrant-landing/content/documentation/platforms/n8n.md

Updated operations ordering as per the recent changes to the node.

docs: Updated descriptions n8n.md

---

qdrant-landing/themes/qdrant-2024/layouts/retrieval-augmented-generation/single.html

Fixed footer logo on [this page](https://deploy-preview-1770--condescending-goldwasser-91acf0.netlify.app/rag/rag-evaluation-guide/)

Fix logo in a small footer

---

qdrant-landing/content/contact-us/_index.md
qdrant-landing/themes/qdrant-2024/assets/css/partials/_contact-form.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_hubspot-form.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/hubspot-form.html

To make functionality appear on the site, it's required to make a corresponding update in the HubSpot form settings.

Toggling form legel disclamers

---

qdrant-landing/content/documentation/cloud-getting-started.md
qdrant-landing/content/documentation/cloud/_index.md
qdrant-landing/content/documentation/cloud/cluster-monitoring.md
qdrant-landing/content/documentation/cloud/cluster-scaling.md
qdrant-landing/content/documentation/cloud/cluster-upgrades.md
qdrant-landing/content/documentation/cloud/configure-cluster.md
qdrant-landing/content/documentation/cloud/create-cluster.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/hybrid-cloud/configure-scale-upgrade.md
qdrant-landing/content/documentation/hybrid-cloud/hybrid-cloud-cluster-creation.md
qdrant-landing/content/documentation/hybrid-cloud/operator-configuration.md
qdrant-landing/content/documentation/private-cloud/qdrant-cluster-management.md

* Documentation page for the different cluster configuration options
* Add RBAC and IaC to getting started
* Docs for automatic shard rebalancing in cloud
* Docs for restart policy in cloud

Improvements for cloud docs

---

qdrant-landing/content/security/bug-bounty-program.md

As requested in https://qdrant.atlassian.net/browse/EMT-159

[EMT-159] fix: Refer to new JSM portal in bug bounty program 

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/voltagent.md

I added VoltAgent - an open source AI Agent framework integration guide to the docs.

docs(integration): add VoltAgent framework documentation and integration guide

---

qdrant-landing/content/documentation/tutorials-and-examples/hybrid-cloud-prometheus.md

Add tutorial on how to monitor Qdrant Hybrid & Private Cloud clusters with Prometheus and Grafana

---

qdrant-landing/content/documentation/guides/common-errors.md
qdrant-landing/content/documentation/guides/installation.md

Preview https://deploy-preview-1864--condescending-goldwasser-91acf0.netlify.app/documentation/guides/common-errors/#incompatible-file-system

troubleshooting windows docker mount

---

qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/http.md
qdrant-landing/static/llms-full.txt

I tried to copy and run the example, but I got an parsing error. Turns out there was a typo!

Fix typo: Score boosting section
