qdrant-landing/content/benchmarks/_index.md
qdrant-landing/themes/qdrant/layouts/partials/seo_schema.html

Added SEO schema (aka schema.org) for articles and benchmark page (`article` entity). Now schema generates from article parameters but also can be overridden with the `seo_schema` param. The `organization` entity now used only on the main page. 
Also, the `seo_schema` parameter can be optionally used on other pages.

Different seo schema for differen pages

---

qdrant-landing/content/articles/product-quantization.md

This PR fixes a broken link in the Product Quantization article.

Fix broken link in PQ article

---

qdrant-landing/content/documentation/guides/security.md

@davidmyriel I wasn't sure if this was still in your queue. Adding this PR just to be sure it gets included.
I'm not sure if this is the correct place to edit this since the recent changes anyway.

Mention the certificate TTL is currently only supported for REST

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/filtering.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/optimizer.md
qdrant-landing/content/documentation/concepts/payload.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/search.md
qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/concepts/storage.md
qdrant-landing/content/documentation/guides/administration.md
qdrant-landing/content/documentation/guides/configuration.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/installation.md
qdrant-landing/content/documentation/guides/monitoring.md
qdrant-landing/content/documentation/guides/quantization.md
qdrant-landing/content/documentation/guides/security.md
qdrant-landing/content/documentation/guides/telemetry.md
qdrant-landing/content/documentation/quick-start.md

In order to avoid indexing/ranking issues with the search engines, I fixed path aliases to keep the indexes connected to the same content.
The only pages that aren't the same are "Integrations" and "How-Tos". Those have been separated into multiple topics. I hope that doesn't cause any issues.

fix aliases for SEO

---

qdrant-landing/content/documentation/tutorials/_index.md
qdrant-landing/content/documentation/tutorials/q101-getting-started.md
qdrant-landing/content/documentation/tutorials/q101-text-data.md

add links to two jupyter notebook tutorials to show on the tutorials index and individual sidebar links

add two notebook tutorials

---

qdrant-landing/content/documentation/integrations/langchain.md

Some users reported our examples were using deprecated parameters. This is fixed now, and I also included more examples of using Langchain with different Qdrant deployment modes.

Fix langchain docs

---

qdrant-landing/README.md
qdrant-landing/themes/qdrant/layouts/partials/docs_sidebar.html

Additionally, to the standard Hugo front matter params, we have the following:
```yaml
hideInSidebar: true
```
If `true`, the page will not be shown in the sidebar. It can be used in regular documentation pages and in documentation section pages (_index.md).

Added hideInSidebare option to docs sidebar

---

qdrant-landing/content/documentation/concepts/snapshots.md

I updated the docs of snapshot recovery, as they were inaccurate. Recovery via API is also possible for single node deployments.

Fix the description of the snapshot recovery

---

qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/guides/configuration.md

Draft for documentation on the customizable temporary directory feature.
I'm not sure if I like it being placed here, but I don't have a better suggestion. Any ideas? Putting it in _Configuration_ or in a _Tutorial_ section could be an option.

Document customizable temporary directory

---

qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/search.md

qdrant-client does not have `with_vector` argument, instead it has `with_vectors`

fix: fix with_vectors arg in python examples

---

qdrant-landing/content/documentation/guides/security.md

This adds an (important) warning for users to protect their internal gRPC ports, used for cluster communication in distributed mode. These are not protected by an API key, which may be unexpected.
I'm not 100% happy with this text. @davidmyriel Maybe you can improve it a bit if you'd like.

Add warning to protect internal gRPC ports

---

qdrant-landing/content/features/filterable.md
qdrant-landing/content/solutions/recommendation-engine.md

A few obvious errors as pointed out by Dave:
-filtrable is a word, although not common and easily mistaken for an error 
-other issue is of grammatical nature in the recommendations section

fix copy content on homepage

---

qdrant-landing/content/documentation/examples.md

The link is duplicated and points to the wrong notebook. This PR removes it.

Fix: Remove duplicated entry from the examples

---

qdrant-landing/content/documentation/concepts/search.md

This PR makes the examples consistent with the API. The issue was reported here: https://github.com/qdrant/qdrant/issues/2325

Fix using `collection_name` in group requests

---

qdrant-landing/content/documentation/concepts/collections.md

Depends on <https://github.com/qdrant/qdrant/pull/2097>. Tracking issue: https://github.com/qdrant/qdrant/issues/2088
This documents a new feature allowing users to edit more collection parameters at runtime (such as HNSW and quantization configurations).

Document edit collection parameters

---

qdrant-landing/content/documentation/integrations/llama-index.md

This PR changes the example of using LlamaIndex. We need a more comprehensive example, and I'll suggest one in a separate PR.

Use QdrantVectorStore instead of GPTQdrantIndex that was removed from LI

---

qdrant-landing/content/documentation/concepts/search.md
qdrant-landing/content/documentation/quick-start.md

Clearly note that retrieval methods, such as search, don't return payload or vector data by default. Also point to information on how to enable it if desired.
I've seen various user reports on that this is unexpected and that it could be stated better. This attempts to improve that.

Clearly note that searches don't include payload/vector data by default

---

qdrant-landing/content/documentation/guides/configuration.md

Cleanup documentation following the removal of the `debug` configuration key in https://github.com/qdrant/qdrant/pull/2339

Remove obsolete debug configuration

---

qdrant-landing/themes/qdrant/layouts/articles/single.html
qdrant-landing/themes/qdrant/layouts/case-studies/single.html

Adds alt text for cover images.
By adding alt text to images we can ensure that a webpage conforms to basic [accessibility guidelines](https://www.w3.org/TR/WCAG20-TECHS/H37.html). It also helps search engines [discover and index images](https://developers.google.com/search/docs/appearance/google-images#descriptive-alt-text%20descriptive-titles-captions-filenames).

Add alt text for article cover image

---

qdrant-landing/content/documentation/cloud/_index.md

- Fixes link giving 404
- Uses Hugo `ref` shortcode to link other content pages.
#276 
From https://gohugo.io/content-management/cross-references/
> The `ref` and `relref` shortcodes display the absolute and relative permalinks to a document, respectively.
- This is applicable to editors who are not familiar with Hugo shortcode and use Netlify CMS. While editing `qdrant-landing\content\documentation\cloud\_index.md`, they may see some strange strings like: 
```go
{{< ref "/documentation/cloud/quickstart-cloud" >}}
```
They should don't delete these since these shortcodes link to other pages.
- Please see the note for maintainers here: #276.

Fix 404 link and use ref shortcode to refer to other pages

---

netlify.toml

Fixes redundant environment variable specification (across contexts) in `netlify.toml`.
The environment variable `HUGO_VERSION` holds the same value for all contexts (production, deploy-preview). Specifying it separately for each context becomes redundant.
Specifying it once under `[build.environment]` should be enough.
From https://docs.netlify.com/configure-builds/file-based-configuration/#deploy-contexts :
>any property of a context-aware key, such as [build] or [[plugins]], will be applied to all contexts unless the same property key is present in a more specific context.

ci: fix redundant environment variable specification in `netlify.toml`

---

qdrant-landing/content/documentation/concepts/points.md

Documents the new update batch points operation. 
Available operations to batch are listed, and an example is given covering all operations.
I added the section to the bottom of the page.

Document update batch points

---

qdrant-landing/content/documentation/concepts/points.md

Mentions that a acknowledged request that is not waited upon might even fail, even though the API responds with HTTP 200.
I've also rewritten this text a bit to make it, in my opinion, a bit more readable.

Rewrite text for acknowledged operations, mention that they might fail

---

qdrant-landing/content/documentation/guides/common-errors.md

Describes how a stack trace can be extracted and attached to an issue report to help us debug _stuck_ scenarios.

Document stack trace in troubleshooting

---

qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/guides/common-errors.md

Adds a troubleshooting guide to get an insight on optimization status for collections that are always yellow.
Also added these fancy colors:

Troubleshoot yellow collection with optimizer log

---

qdrant-landing/themes/qdrant/layouts/partials/table_of_content.html

Deprecated conditions led to missing TOC on the top-level pages of sections, removed them to fix the problem.

Removed deprecated conditions in the TOC template

---

qdrant-landing/content/documentation/concepts/collections.md

We've had some support questions on how to update vector parameters in a collection that does not have named vectors.
This adds a note that in such case, an empty vector name is used.

Describe how to update collection parameters for unnamed vector

---

qdrant-landing/content/documentation/concepts/storage.md

From:
> To enable this, you need to set the `hnsw_config.on_disk` parameter to `true` during [creation](https://qdrant.tech/documentation/concepts/collections/#create-a-collection) of the collection.
To:
> To enable this, you need to set the `hnsw_config.on_disk` parameter to `true` during collection [creation](https://qdrant.tech/documentation/concepts/collections/#create-a-collection) or [updating](https://qdrant.tech/documentation/concepts/collections/#update-collection-parameters).

The HNSW on_disk flag can also be set when updating collection params

---

qdrant-landing/themes/qdrant/layouts/articles/single.html
qdrant-landing/themes/qdrant/layouts/documentation/list.html
qdrant-landing/themes/qdrant/layouts/documentation/single.html
qdrant-landing/themes/qdrant/static/js/script.js

This PR adds wrapping tables on documentation pages and on single articles pages into `div.table-responsive`.
Tried variants with js and regex, the second one seems to be better because of working on the building step, which guarantees not to affect user experience.

Wrapped tables

---

qdrant-landing/content/documentation/concepts/filtering.md

Change the order of `lon` and `lat` as it is defined in this order in the codebase. This is a very minor issue but it is good  to have everything consistant.
Add GeoPolygon examples to documentation

Add query geo polygon docs

---

qdrant-landing/content/documentation/concepts/collections.md

In [Collections page](https://qdrant.tech/documentation/concepts/collections/#list-all-collections) of the documentation, the referred python function for getting the collection alias name is wrong. I couldn't find when it was changed from `list_collection_aliases` to `get_collection_aliases`, but it no longer exists on the codebase. The correct function is `get_collection_aliases` ([link](https://github.com/qdrant/qdrant-client/blob/82ecb104ed919596d7753c1a31017dfada8d3e02/qdrant_client/client_base.py#L221)).
* Change referred method from `list_collection_aliases` to `get_collection_aliases`.

Update collections.md to correct list collection aliases section

---

qdrant-landing/content/documentation/quick-start.md

In our quick start guide, we only linked to the API URL after starting the Qdrant container. This adds a link to the Web UI as well.
At the bottom:

Add link to Web UI in quick start guide

---

qdrant-landing/content/documentation/concepts/snapshots.md

The variable name used in config is `snapshots_path`. Hence the related ENV variables is `QDRANT__STORAGE__SNAPSHOTS_PATH`.
Using `QDRANT__STORAGE__SNAPSHOT_PATH` doesn't work.

Fixed variable name

---

qdrant-landing/content/documentation/concepts/search.md

The `with_payload` field also supports using an array directly, without explicit `include`/`exclude` usage.
For example:
```json
{
"with_payload": ["city"]
}
```

Update `with_payload` examples, also describe using an array directly

---

qdrant-landing/themes/qdrant/layouts/_default/single.html

Fixes <https://github.com/qdrant/landing_page/issues/346>
Add an automatic redirect on `external_url` pages.
This change now shows the following redirection text on empty pages and immediately redirects the user to the external URL on visit:
Rendered: https://deploy-preview-347--condescending-goldwasser-91acf0.netlify.app/documentation/api-reference

On `external_url` pages, add redirect in rendered HTML

---

qdrant-landing/themes/qdrant/layouts/partials/js.html
qdrant-landing/themes/qdrant/layouts/partials/table_of_content.html

When a user clicks on a table of contents, the page will smoothly scroll to the corresponding section.

Smooth scroll on clicking into TOC

---

qdrant-landing/content/documentation/concepts/collections.md

Leads to https://qdrant.tech/documentation/concepts/collections/optimizer/ instead of https://qdrant.tech/documentation/concepts/optimizer/.

fix: broken link at concepts/collections

---

qdrant-landing/content/documentation/concepts/collections.md

In https://qdrant.tech/documentation/concepts/collections/#create-a-collection, the python example suggests `client.recreate_collection()` which users will take as default. However `recreate` is a client utility for deleting and creating a collection with the same name. It has been a problem for some Discord users who are confused by their collection being deleted.
The utility is useful but I think the introduction to collection creation should not be the place to showcase it.
There are other occurrences of `recreate_collection` in other examples, but I'm not sure if we should change all of them now.

Create a collection: `recreate_collection` -> `create_collection`

---

qdrant-landing/content/documentation/faq/database-optimization.md
qdrant-landing/content/documentation/faq/qdrant-fundamentals.md
qdrant-landing/content/documentation/guides/administration.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/multiple-partitions.md
qdrant-landing/content/documentation/guides/optimize.md
qdrant-landing/content/documentation/guides/quantization.md
qdrant-landing/content/documentation/guides/security.md

This PR covers all the Python examples in Documentation / Guides with their counterparts in TypeScript.

Add TypeScript examples for Documentation / Guides

---

qdrant-landing/config.toml

One of the GH actions was failing due to the recent release of Hugo.
See: https://github.com/qdrant/landing_page/actions/runs/6704856656/job/18218119886?pr=376
This PR changes the config.toml, so all the variables are exposed properly.

Fix rendering RSS in Hugo 0.120.1

---

qdrant-landing/content/documentation/tutorials/neural-search.md

I opened issue #404 about a typo in the [Create a Simple Neural Search Service](https://qdrant.tech/documentation/tutorials/neural-search) tutorial.
```
city_of_interest = "Berlin"
city_filter = Filter(**{
"must": [{
"key": "city", # Store city information in a field of the same name 
"match": { # This condition checks if payload field has the requested value
"value": "city_of_interest"
}
}]
})
```
I fixed the typo by replacing the line:
`                "value": "city_of_interest"`
with:
`                "value": city_of_interest`

Fixed typo in the neural-search.md tutorial

---

qdrant-landing/content/documentation/integrations/jina-embeddings.md

Hey Qdrant team!
We just launched [Jina Embeddings](https://jina.ai/#enterprises) and would love to add them as an integration to your docs.
We also plan to make our models available through FastEmbed, so stay tuned for that PR as well.
Cheers!

Add jina embeddings to integrations

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

Tim and I wanted to improve this section of the docs since we had a little trouble understanding it initially (it is a very complex topic!) I ended up reviewing the whole page in the process and made the following changes:
* Changed the phrasing of some sentences to be a little clearer, including adding missing articles and changing tense.
* In the "sharding" section, added some extra details about Qdrant not automatically rebalancing shards
* Changed "Scaling replication factor" to "Creating new shard replicas" to point out that changing replication_factor won't create new replicas; you have to perform a replicate_shard operation.
* Capitalized Qdrant
* Trimmed trailing spaces

Rephrase sections of the distributed deployment page

---

qdrant-landing/content/documentation/integrations/privategpt.md

Updates the PrivateGPT integration docs to reflect the latest changes made in https://github.com/imartinez/privateGPT/pull/1285.

docs: Update privategpt integration docs

---

qdrant-landing/content/documentation/concepts/collections.md

Not everyone knows what's multitenancy -- and it's used in different contents (I'm used to the definition in Identity Management).
I think it'd help readers to have a link to an authoritative reference, so I propose adding one from IBM, https://www.ibm.com/topics/multi-tenant.

Multitenancy: add link to authoritative definition

---

qdrant-landing/content/articles/memory-consumption.md
qdrant-landing/content/articles/new-recommendation-api.md
qdrant-landing/content/articles/qdrant-1.3.x.md
qdrant-landing/content/documentation/concepts/collections.md
qdrant-landing/content/documentation/concepts/filtering.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/payload.md
qdrant-landing/content/documentation/concepts/points.md
qdrant-landing/content/documentation/concepts/search.md
qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/concepts/storage.md
qdrant-landing/content/documentation/guides/distributed_deployment.md
qdrant-landing/content/documentation/guides/multiple-partitions.md
qdrant-landing/content/documentation/guides/optimize.md
qdrant-landing/content/documentation/guides/quantization.md
qdrant-landing/content/documentation/tutorials/bulk-upload.md

This removes the empty line in HTTP examples between the method/path and body.
I've done this because our Web UI doesn't support this formatting:

Remove empty lines in HTTP examples, reformat some of them

---

qdrant-landing/README.md

The paths in the `sass` commands were wrong. The user is instructed to change into the `qdrant-landing` directory, so we don't have to provide this in the `sass` invocation.

Fix incorrect paths in sass command

---

qdrant-landing/content/documentation/concepts/snapshots.md

Document the snapshot priority parameter, link to it from the recovery section and give an example of use.
This is an important parameter which can gave a significant effect on the end result of recovery. We didn't document it. This PR now describes it.
Rendered section: https://deploy-preview-428--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/snapshots/#snapshot-priority
I've also added an info box linking to the new section here: https://deploy-preview-428--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/snapshots/#recover-via-api

Document snapshot priority

---

qdrant-landing/content/documentation/concepts/collections.md

Describe that point and vector counts shown in the collection info are approximate. Tell users not to rely on these numbers, and briefly explain why.
We can point users to this section if questions are asked about these counts. We've had quite a bunch of these.
Rendered: https://deploy-preview-443--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/collections/#approximate-point-and-vector-counts

Add approximate point and vector counts section

---

qdrant-landing/content/documentation/guides/configuration.md

This updates the configuration in our documentation to what we have in Qdrant 1.7.0.
Since this is copy-paste, it's fine to merge this right after the first approval. :+1:

Update configuration to Qdrant v1.7.0

---

qdrant-landing/content/documentation/concepts/search.md

I did a bad merge in <https://github.com/qdrant/landing_page/pull/408>, this patches it.
It also links the recommendation mentions on the search page to their respective section.

Patch bad merge in recent PR, link to recommendation API

---

qdrant-landing/content/documentation/concepts/collections.md

We talk about approximate point counts, but we also have an exact count API, so let's tell users about it.
Rendered (at the bottom): https://deploy-preview-451--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/collections/#approximate-point-and-vector-counts

From approximate point counts section, link to point API

---

qdrant-landing/content/articles/qdrant-1.7.x.md

We're about to publish the sparse vectors article. I suggest to link to it from the 1.7 release article, as it may result in more traffic.
Rendered at the bottom of this section: https://deploy-preview-460--condescending-goldwasser-91acf0.netlify.app/articles/qdrant-1.7.x/#sparse-vectors

From release article, link to sparse vectors article

---

qdrant-landing/content/documentation/embeddings/gemini.md

The linked is fixed according to @atarora suggestion on Slack.

Fix BQ link in Gemini integration docs

---

qdrant-landing/content/documentation/frameworks/langchain.md

Fix typo in langchain.md

---

qdrant-landing/content/documentation/concepts/snapshots.md

Snapshot documentation has been updated, so it clearly states that they must be created separately on each node within a cluster. Previously, this could have been misleading.

Update documentation about snapshots

---

qdrant-landing/content/documentation/cloud/quickstart-cloud.md
qdrant-landing/content/documentation/concepts/explore.md
qdrant-landing/content/documentation/concepts/search.md
qdrant-landing/content/documentation/guides/quantization.md

This PR fixes some Rust client usage examples and adds missing examples of `1.7` features.

docs: Rust client usage update

---

qdrant-landing/config.toml

The current home page includes a link from Resources -> Blog to blog.qdrant.tech. That seems out of date

Update Resources -> Blog link on home page

---

.lycheeignore
qdrant-landing/content/articles/serverless.md

Based on @generall 's request in https://github.com/qdrant/landing_page/issues/488#issuecomment-1879668074
I could also add the URLs for the 403s to .lycheeignore

Correct link errors from issue #488. Add URLs to exclude list

---

qdrant-landing/content/blog/qdrant-updated-benchmarks-2024.md

The links currently redirect to https://qdrant.tech/blog/qdrant-benchmarks-2024/qdrant.tech/benchmarks and https://qdrant.tech/blog/qdrant-benchmarks-2024/github.com/qdrant/vector-db-benchmark.

fix: Broken links qdrant-updated-benchmarks-2024.md

---

qdrant-landing/content/documentation/datasets.md

Fixes HF logo overflow on mobile at https://qdrant.tech/documentation/datasets/.

fix: HuggingFace logo overflow

---

qdrant-landing/config.toml
qdrant-landing/themes/qdrant/layouts/partials/feedback.html

@generall @mjang it's appeared that we should not trigger GA events programmatically, and will do it from GTM interface. You can ask @Alyonkka for additional information.
In this PR: removed `sendFeedback` function and it's call because we need to do it from GTM UI, not programmatically.

Removed sendFeedback function

---

qdrant-landing/content/blog/what-is-a-vector-database.md

Our latest article has some issues rendering bold text. This PR fixes that.
Old:
New:
Rendered: https://deploy-preview-553--condescending-goldwasser-91acf0.netlify.app/blog/what-is-a-vector-database/#what-is-similarity-search

Fix bold text in latest article

---

qdrant-landing/content/documentation/concepts/_index.md

I'd like us to present an overview of all concepts shown in our docs. With this PR, I've set this up as a table, with links to each concept.
Build of new page: https://deploy-preview-559--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/

Set up an index page for concepts

---

qdrant-landing/content/documentation/interfaces.md

The docs cite "official clients" in several locations. I've included "official clients" in the [Interfaces](https://qdrant.tech/documentation/interfaces/) page, to reflect my understanding from @generall .
Anyone who uses our search text box to search for "official clients" should then see it on the Interfaces page.

Reference to 'Official' clients

---

qdrant-landing/config.toml

Added a link to the trust center under the Resources submenu:

Link to the trust center

---

qdrant-landing/themes/qdrant/layouts/partials/feedback.html
qdrant-landing/themes/qdrant/layouts/partials/table_of_content.html

This will allow for correct path in the GitHub URLs on Windows systems in development.

docs: Correct path in the GitHub feedback links on Windows systems.

---

qdrant-landing/content/documentation/frameworks/airflow.md

Hi Anush, 
We need to use the "official" name of the project, "Apache Airflow". While I was in the file, I updated a few other things.
Note: the link checker build failure is due to a Hugo versioning problem. We're working on that.
(The build still works: https://deploy-preview-624--condescending-goldwasser-91acf0.netlify.app/documentation/frameworks/airflow/ )

Correct official name

---

qdrant-landing/content/documentation/concepts/snapshots.md
qdrant-landing/content/documentation/tutorials/create-snapshot.md

After working with a Qdrant Cloud customer to transfer data to a new cluster, they found it difficult to follow our current docs due to the mixture of instructions that only apply to Qdrant Cloud and instructions that only apply to self-hosted Qdrant. They also had some trouble with `curl` syntax and the difference between the "restore" vs. "upload and restore" endpoints.
So I've reworked the page with the following changes:
* Mention backups as an alternative to snapshots for Qdrant Cloud users
* Split the restoration section into 3 sections based on the 3 methods, calling out specifically the use-cases for each method
* Explain how the snapshot upload API can accept a remote URL or a file URI
* Mention that missing collections are automatically created during restore
* Link to the API …

Rework the snapshots page for clarity

---

qdrant-landing/content/documentation/frameworks/spark.md

Updates the Spark connector docs as per https://github.com/qdrant/qdrant-spark/releases/tag/v2.0.0.

docs: Updated spark.md after the 2.0.0 release

---

qdrant-landing/content/documentation/frameworks/spark.md

Updates the docs as per the https://github.com/qdrant/qdrant-spark/releases/tag/v2.1.0 release.
The snippets have been tested.

docs: Spark connector usage update

---

qdrant-landing/content/blog/_index.md

Not excludes the blog index from site map anymore and fixes this:
> They noticed that our blog homepage has a noindex tag, which we should remove.

Removed sitemapExclude parameter from the blog index

---

qdrant-landing/content/documentation/concepts/points.md

Adds the documentation for the new `order_by` feature for the `scroll` endpoint
Related issue: qdrant/qdrant#3521
Drafting only because it should be merged after v1.8 release

Add documentation for `order_by`

---

qdrant-landing/content/documentation/concepts/filtering.md
qdrant-landing/content/documentation/concepts/indexing.md
qdrant-landing/content/documentation/concepts/payload.md

Related issue: https://github.com/qdrant/qdrant/issues/3320.

Add documentation for `datetime` payload (v1.8)

---

qdrant-landing/content/documentation/concepts/payload.md

Some more notes about the `datetime` format that are worth mentioning

Add more datetime format notes

---

qdrant-landing/content/documentation/tutorials/code-search.md

1. `https://github.com/qdrant/code-search-demo` -> `https://github.com/qdrant/demo-code-search`
2. `https://code-search-demo.qdrant.tech/` -> `https://code-search.qdrant.tech/`

Fix typos in qdrant-landing/content/documentation/tutorials/code-search.md

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

Based on the slack thread in cloud-dev on March 4th, I've added some extra details about distributed setups.
Since we have Qdrant Cloud maintenance scheduled soon, some users are wanting to know exactly what to do to make their clusters highly available, and want to know exactly what happens when one node goes down temporarily.

Add advice about number of nodes to distributed_deployment

---

qdrant-landing/content/documentation/tutorials/create-snapshot.md

Hi @joekrejci . I agree, this tutorial should serve your purpose. The [Restore from snapshot](https://qdrant.tech/documentation/tutorials/create-snapshot/#restore-from-snapshot) section already suggests that you can use the steps to restore info to a new cluster.
I've added a paragraph which should be consumed by our search interface, so we won't have trouble finding info for your use case in the future.

Update tutorial to describe migration

---

qdrant-landing/content/documentation/concepts/indexing.md

Documentation for Qdrant 1.8.
This documents the parameterized integer index added in <https://github.com/qdrant/qdrant/pull/3380>.
It is a specialized integer index type, that some might want to use for further fine-tuning. Generally speaking it is recommended to use the standard integer index without parameters.
Rendered: https://deploy-preview-520--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/indexing/#integer-index-parameters

Documentation for parameterized integer index

---

qdrant-landing/content/documentation/tutorials/llama-index-multitenancy.md

Starting v0.10 [llama-index](https://github.com/run-llama/llama_index/releases/tag/v0.10.1) is split between llama_index and llama_index.core libraries. This commit updates documentation to work with llama-index v0.10 and higher. Also this commit adds note on how to run it with local llamaIndex model (like llama.cpp)

Update llama-index-multitenancy.md to work with llama-index v0.10

---

qdrant-landing/assets/schema/product-schema.json

Even though schema.org validated our updated structured data, google disagrees: using words to describe low and high prices is invalid.
So here the `lowPrice` is set to 0 and the `highPrice` field is removed (until we won't come up with a better solution).

Fix for the product schema

---

qdrant-landing/themes/qdrant-2024/assets/css/_theme-variables.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-articles-posts.html

I propose to change a little bit bootstrap gutters to make them closer to the design in Figma. And then we can use `.row > .col` for posts list

Custom gutters

---

qdrant-landing/content/documentation/guides/multiple-partitions.md

This commit add the information that the key don't need to be called group_id.

feat: add information about the group_id key:

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

Tracked in: <https://github.com/qdrant/qdrant/issues/3477>
Documents a new `wal_delta` transfer method.
It'll be enabled by default in Qdrant 1.9, and so I suggest to merge this when we're doing the release.
Rendered: https://deploy-preview-736--condescending-goldwasser-91acf0.netlify.app/documentation/guides/distributed_deployment/#shard-transfer-method

Document WAL delta transfer for Qdrant 1.9

---

qdrant-landing/content/documentation/concepts/snapshots.md

Full storage snapshots are not suitable to be used with distributed mode.
I've added an alert box to make this clear.
We may eventually deprecate parts of this, but until then this will be a useful addition.
Rendered: https://deploy-preview-826--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/snapshots/#snapshots-for-the-whole-storage

Docs: full storage snapshots are not for distributed mode

---

qdrant-landing/content/headless/footer.md
qdrant-landing/themes/qdrant-2024/layouts/_default/baseof.html
qdrant-landing/themes/qdrant-2024/layouts/_default/single.html
qdrant-landing/themes/qdrant-2024/layouts/partials/article-content.html
qdrant-landing/themes/qdrant-2024/layouts/partials/head.html
qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-post.html

Added a default single page layout (which means terms, privacy policy, etc pages work now), moved an article content in the separate partial to reuse, fixed table inside posts.

Single page default layout, article content partial, table

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

Based on this conversation: https://qdrant.slack.com/archives/C04KX0FSW8G/p1715977792502279
This PR expands our recommendations about shard count, including a focus on horizontal scaling. When you horizontally scale, you have to have enough shards for each node, or you have to recreate the collection. So telling everyone to use at least 2x shards per node allows for expansion, with 12 shards being a good round number for most use-cases.

Expand advice on shard count and horizontal scaling

---

qdrant-landing/content/documentation/hybrid-cloud/operator-configuration.md

We were missing indenting two lines to give the YAML code proper structure (found while working on the operator's config validation 😅 ) specifically on the `namespaceSelector` > `matchLabels`

Add proper indentation to operator-config

---

qdrant-landing/content/documentation/concepts/filtering.md

The JSON isn't valid without the comma.

Add missing comma in filtering.md

---

qdrant-landing/content/documentation/frameworks/langchain.md

langchain has split their packages up a bit, so the prior code examples no longer work.
There is also a `langchain-qdrant` package, which can also be used to access `Qdrant`, but we would have still needed to instruct the user to install `langchain-community` in order to get the huggingface embeddings, so this is the simplest walkthrough I could imagine.

docs: updated langchain usage

---

qdrant-landing/themes/qdrant-2024/assets/css/base.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_docs-menu.scss
qdrant-landing/themes/qdrant-2024/assets/css/partials/_go-to-top-button.scss
qdrant-landing/themes/qdrant-2024/assets/js/helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/layouts/_default/baseof.html
qdrant-landing/themes/qdrant-2024/layouts/partials/go-to-top-button.html

PR adds a button to scroll to the top of documentation, articles (post only), blogs (post only), and benchmark pages.

Go to top button

---

qdrant-landing/content/documentation/guides/configuration.md

Reverts qdrant/landing_page#543
The counterpart of that PR was not merged. This config is therefore incorrect.

Revert "Add S3 config into example"

---

qdrant-landing/content/documentation/concepts/snapshots.md

This PR does two things:
- it describes the ability to store snapshots in S3-compatible storage
- it moves the section describing snapshot storage down, splitting it in a local file system and S3 section
Rendered: <https://deploy-preview-994--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/snapshots/#storage>

Qdrant 1.10.0: document S3 snapshots, reorganize storage text

---

qdrant-landing/content/documentation/guides/configuration.md
qdrant-landing/content/headless/stats.md

Update the configuration to match the Qdrant 1.10.0 release.
This removes the more elaborate S3 configuration example, but I'll move it into a different place in a [separate PR](https://github.com/qdrant/landing_page/pull/994).

Qdrant 1.10.0: update configuration

---

qdrant-landing/config.toml
qdrant-landing/themes/qdrant-2024/assets/js/cookit.js
qdrant-landing/themes/qdrant-2024/assets/js/helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/assets/js/segment-helpers.js
qdrant-landing/themes/qdrant-2024/layouts/partials/head.html
qdrant-landing/themes/qdrant-2024/layouts/partials/hero.html
qdrant-landing/themes/qdrant-2024/layouts/partials/menu.html
qdrant-landing/themes/qdrant-2024/layouts/partials/top-banner.html

We are introducing Segment to the Marketing site for the sake of better Marketing/Growth Analytics [notion file](https://www.notion.so/qdrant/Data-ELT-Pipeline-Warehousing-with-Segment-Postgres-5f6807c20c0e4e5eb340ef49ed0b74a3). Users' events/behavior will be stored in Mixpanel and a Postgres Warehouse solution to tie it together with our other (business, CRM) analytics.
We are loading Segment on the frontend when a user consents to tracking via the cookit.js banner. In the future we will likely implement Segment on the backend which will only require removing the Segment injection logic and swapping Segment's front end calls for backend endpoint API calls.

initial commit for segment introduction

---

qdrant-landing/themes/qdrant-2024/layouts/partials/table-of-contents.html

`hideTOC: true` in the front matter of markdown file will hide TOC

Added hide TOC param

---

qdrant-landing/content/documentation/concepts/points.md

I believe we recently changed our logic to not do this anymore.
We deduplicate by point IDs and don't allow duplicate IDs anymore.

Remove note about getting duplicate points if matching multiple payloads

---

qdrant-landing/content/documentation/guides/security.md

Since it's possible to perform an SSRF attack via snapshot recovery (a known and accepted risk), it's important to tell users how to prevent that.

Add info about network hardening for Qdrant

---

qdrant-landing/content/articles/binary-quantization.md

Recently a user pointed out that this paragraph was a little ambiguous. [(Discord link)](https://discord.com/channels/907569970500743200/1262851211577790565/1262857341255286804)
The main idea is that users can decide what is on RAM and what is on disk, so quantizing vectors for less RAM usage requires to set the original vectors on disk.
Also, when using quantization, HNSW is built with the quantized vectors, while the text hints that there are two separate HNSW graphs.

nit in binary quantization article

---

qdrant-landing/content/documentation/1-dl.md
qdrant-landing/content/documentation/3-dl.md
qdrant-landing/content/documentation/4-dl.md
qdrant-landing/content/documentation/5-dl.md
qdrant-landing/content/documentation/_index.md
qdrant-landing/content/documentation/cloud/_index.md
qdrant-landing/content/documentation/community-links.md
qdrant-landing/content/documentation/concepts/_index.md
qdrant-landing/content/documentation/datasets.md
qdrant-landing/content/documentation/embeddings/_index.md
qdrant-landing/content/documentation/examples/_index.md
qdrant-landing/content/documentation/faq/_index.md
qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/spark.md
qdrant-landing/content/documentation/guides/_index.md
qdrant-landing/content/documentation/hybrid-cloud/_index.md
qdrant-landing/content/documentation/interfaces/_index.md
qdrant-landing/content/documentation/interfaces/api-reference.md
qdrant-landing/content/documentation/interfaces/web-ui.md
qdrant-landing/content/documentation/overview/_index.md
qdrant-landing/content/documentation/quickstart-cloud.md
qdrant-landing/content/documentation/quickstart.md
qdrant-landing/content/documentation/release-notes.md
qdrant-landing/content/documentation/send-data/_index.md
qdrant-landing/content/documentation/send-data/data-streaming-kafka-qdrant.md
qdrant-landing/content/documentation/send-data/databricks.md
qdrant-landing/content/documentation/send-data/qdrant-airflow-astronomer.md
qdrant-landing/content/documentation/tutorials/_index.md

[PREVIEW](https://deploy-preview-1046--condescending-goldwasser-91acf0.netlify.app/documentation/send-data/)
- I fixed all the weights in each markdown file and left space for new sections
- I combined API + SDK in one section to save space
- I removed Community Contributions old page from Support
- Introduced a special examples section "Send Data to Qdrant". This will have examples on how to populate Qdrant OR migrate from other DBs
- Turned the old examples section into "Build Prototypes". I will further divide this into "Build Vector Search Apps" and "Build RAG apps"
- We need to separate the sections because visitors to the website won't browse through long tables. We need to make the headings immediately obvious to the reader.

Fix Sidebar + Add a New Section: "Send Data to Qdrant"

---

qdrant-landing/themes/qdrant-2024/assets/js/helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/assets/js/segment-helpers.js

Marketing needs to track a user's journey across our 2 domains: `qdrant.tech` and `cloud.qdrant.io`. To do this without exposing user PII all outbound links to Cloud UI will get a url parameter called `qdrant-tech` with a randomly generated 32 character string. This will allow us to tie together a user's journey across domains via the link href and the referrer parameters within Cloud UI events.
- Wait for DOM Content Loaded
- Update cloud.qdrant.io links with `qdrant-tech` url param
- add new key/value pair to interaction event called `qdrant_tech_hash`
@fabriziobonavita

Cloud UI Outbound Link URL Param

---

qdrant-landing/themes/qdrant-2024/assets/css/partials/_documentation-article.scss

https://qdrant.tech/documentation/tutorials/neural-search/#:~:text=Use%20recreate_collection (SWITCH TO LIGHT MODE)
https://deploy-preview-1057--condescending-goldwasser-91acf0.netlify.app/documentation/tutorials/neural-search/#upload-data-to-qdrant:~:text=Use%20recreate_collection

fix: Poor contrast in <aside> content in light mode

---

qdrant-landing/content/documentation/frameworks/airflow.md
qdrant-landing/content/documentation/quickstart-cloud.md

Fixes the broken highlighted link.
Leads to https://qdrant.tech/documentation/cloud/quickstart-cloud.

fix: Broken cloud quickstart link in welcome letter

---

qdrant-landing/content/documentation/concepts/hybrid-queries.md

Adds documentation for `dbsf` fusion variant. Preview:

Add docs for Distribution-based score fusion

---

qdrant-landing/content/documentation/concepts/hybrid-queries.md
qdrant-landing/content/documentation/concepts/search.md

Targets 1.11
This PR adds the documentation for the query group API.
One issue is that the reference documentation for everything grouping & lookup is done with search.
To avoid duplication, I have added a minimal example and links towards the search API content.
In the future we should move all docs to the query page.
The SDKs examples might contain syntax errors.

Docs for query group API

---

qdrant-landing/themes/qdrant-2024/assets/js/helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/index.js
qdrant-landing/themes/qdrant-2024/assets/js/segment-helpers.js
qdrant-landing/themes/qdrant-2024/layouts/partials/menu-mobile.html

Spoke with Luis and Fabrizio. We've decided to pass the Segment anonymous generated ID via url params for cross domain tracking, instead of the pre-existing generate hash:
- custom generated ID swapped out for Segment Anonymous ID
- tagging on analytics load (instead of DOM load) as Segment must be loaded for the ID retrieved and passed
- adding mobile nav signup/login click tracking

Segment Anonymous ID for Cloud UI Consumption

---

qdrant-landing/content/articles/late-interaction-models.md

Changing the model name, as requested by its author.

Fix typo in the model name

---

qdrant-landing/themes/qdrant-2024/layouts/partials/community-hero.html

The "Join our Discord" button on the community page does not link properly to the Discord invite due to the wrong param being used. This PR fixes the theme to use `url`, instead of `link`, so it matches the param declared in Markdown.

Fix: incorrect param usage in community hero

---

qdrant-landing/archetypes/delimiter.md
qdrant-landing/content/documentation/0-dl.md
qdrant-landing/content/documentation/1-dl.md
qdrant-landing/content/documentation/2-dl.md
qdrant-landing/content/documentation/3-dl.md
qdrant-landing/content/documentation/4-dl.md
qdrant-landing/content/documentation/5-dl.md
qdrant-landing/content/features/_index.md
qdrant-landing/content/legal/_index.html
qdrant-landing/content/legal/_index.md
qdrant-landing/content/marketing/_index.md
qdrant-landing/content/stack/_index.md

We have some markdown files that are not intended to be displayed as site pages. Although they are excluded from the site map, they can still be accessed through a link. This pull request adds Hugo parameters to these files to prevent them from being built.

Prevent empty pages rendering

---

qdrant-landing/content/blog/cohere-embedding-v3.md
qdrant-landing/content/blog/vector-search-and-applications-by-andrey-vasnetsov-cto-at-qdrant.md
qdrant-landing/content/demo/_index.md
qdrant-landing/content/subscribe/_index.md

Removed `sitemapExclude` parameters from associated files as the next pages need to be indexed by search engines now:
- https://qdrant.tech/blog/cohere-embedding-v3/
- https://qdrant.tech/demo/
- https://qdrant.tech/blog/vector-search-and-applications-record/
- https://qdrant.tech/subscribe/

Removed `sitemapExclude` params from places where we don't need it anymore

---

qdrant-landing/layouts/_default/_markup/render-link.html

Render links from markdown to HTML so that they would open in a new tab if they start with `https`.

Open external links in a new tab

---

qdrant-landing/content/documentation/guides/configuration.md
qdrant-landing/content/documentation/hybrid-cloud/networking-logging-monitoring.md

This PR resolves: https://github.com/qdrant/landing_page/issues/1125
Provides documentation around writing Qdrant log files to disk.
I tried to build the project locally to verify but saw the following when I ran `hugo serve -D`:
```
ERROR TOCSS-DART: failed to transform "/css/main.scss" (text/x-scss): "/Users/justin/Development/Projects/landing_page/qdrant-landing/themes/qdrant-2024/assets/css/_bootstrap-custom.scss:2:8": Can't find stylesheet to import.
Built in 1744 ms
Error: error building site: TOCSS-DART: failed to transform "/css/vendor/splide.scss" (text/x-scss): "/Users/justin/Development/Projects/landing_page/qdrant-landing/themes/qdrant-2024/assets/css/vendor/splide.scss:1:8": Can't find stylesheet to import.
```

Adding documentation for specifying writing log files to disk.

---

qdrant-landing/content/documentation/embeddings/mixpeek.md
qdrant-landing/content/documentation/embeddings/mixpeek.mdx

This PR adds documentation and example code for integrating Mixpeek's video embedding capabilities with the Qdrant vector database. This integration allows users to efficiently process, embed, store, and query video content using Mixpeek's `vuse-generic-v1` model and Qdrant's vector search capabilities.
- Detailed instructions for processing video chunks using Mixpeek
- Examples of embedding video chunks and upserting them into Qdrant
- Instructions for performing similarity searches using both text and video queries
- Note on creating the appropriate Qdrant collection for Mixpeek embeddings
- This integration uses Mixpeek's `vuse-generic-v1` model, which produces 768-dimensional embeddings
- Users will need to have a valid Mixpeek API key to use this integration
- The Qdrant collection …

added mixpeek video embedding support

---

qdrant-landing/content/documentation/_index.md

This is a section for long-form technical content that's not accessible from the docsite. 
The articles page has 0 navigation and most people don't actually switch between docs and articles.
This is a temporary solution until we get DevPortal online.

[Docs] Add Developer Guidebooks 

---

qdrant-landing/content/documentation/guides/multiple-partitions.md

Typo is present in python example for creating payload index.
`keywprd` vs `keyword`

Fix typo in multiple-partitions documentation

---

qdrant-landing/content/documentation/qdrant-cloud-api.md

Example API request lacks `apikey` in header
```
-H 'Authorization: <YOUR_API_KEY>'
```
amended to 
```
-H 'Authorization: apikey <YOUR_API_KEY>'
```
I tested and this works

fix: prepend Cloud API KEY with apikey

---

qdrant-landing/content/documentation/concepts/filtering.md

[PREVIEW](https://deploy-preview-1180--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/filtering/)
We are finding documentation is some of the most popular content on the site.
Specifically, filtering is a top 10 visited page. However, for people to discover related filtering tips, they have to manually explore the site.
By referencing directly related content, such as more formal guides (not blogs or casual articles), we aim to give more depth to the user journey on the docsite.

[Docs] Add "Related Content" section in concept docs

---

qdrant-landing/content/documentation/embeddings/jina-embeddings.md

This PR add explanation of an additional field: `late_chunking` to use together with `jina-embeddings-v3`.

docs: add late chunking parameter to Jina AI integration

---

qdrant-landing/assets/jsconfig.json
qdrant-landing/content/documentation/guides/installation.md

[Rendered](https://deploy-preview-1182--condescending-goldwasser-91acf0.netlify.app/documentation/guides/installation/#cpu-and-memory)
Update the listed requirements in the installation guide. We do not support 32-bit systems.

Add CPU requirements, 32-bit is not supported

---

qdrant-landing/content/documentation/quickstart.md

A python user was confused on Discord when following the quickstart to get a different result.
This is because the Python client fetches payload by default.
Regarding other clients, I just checked the Rust one and it does not request payload by default.

Fix quickstart for Python due to fetching payload by default

---

qdrant-landing/content/documentation/concepts/points.md

Fixed a broken link. Updated the link to point to the correct `scroll-points` schema in the API reference.

[Docs] Fix broken link to scroll-points in API reference

---

qdrant-landing/content/documentation/hybrid-cloud/hybrid-cloud-setup.md
qdrant-landing/content/documentation/private-cloud/private-cloud-setup.md

CRDs are now served from `qdrant-kubernetes-api` chart
Followup of https://github.com/qdrant/kubernetes-api/pull/32

Replace occurrences of `qdrant-operator-crds` with `qdrant-kubernetes-api`

---

qdrant-landing/themes/qdrant-2024/assets/js/helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/segment-helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/segment-setup.js
qdrant-landing/themes/qdrant-2024/layouts/partials/js-head.html

Storing and leveraging the Google Measurement ID for conversion analytics for the marketing team. Requested by JDM (consulting agency for our marketing) for use with Google Ads.

Adding GA4 properties to Segment analytics events

---

qdrant-landing/themes/qdrant-2024/assets/css/partials/_top-banner.scss

Small style fix for mobiles:
|**Before**| **After**|
|--|--|
|![Screenshot 2024-11-05 at 16 01 41](https://github.com/user-attachments/assets/19bf0385-57e3-4462-8aef-934bfaedbc73)| ![Screenshot 2024-11-05 at 16 01 49](https://github.com/user-attachments/assets/b42efd51-bfde-4cd5-8a27-776891e7892b)|

top banner mobile style fix

---

qdrant-landing/config.toml
qdrant-landing/content/headless/docs-feedback.md
qdrant-landing/themes/qdrant-2024/assets/css/partials/documentation/_docs-feedback.scss
qdrant-landing/themes/qdrant-2024/layouts/partials/documentation/feedback.html

This PR restores the feedback button functionality from the old template. After it's merged, it can be required to update GTM triggers.

Feedback buttons functionality

---

qdrant-landing/content/documentation/fastembed/_index.md
qdrant-landing/content/documentation/interfaces.md
qdrant-landing/content/documentation/interfaces/api-reference.md
qdrant-landing/content/documentation/quickstart.md
qdrant-landing/content/documentation/web-ui.md

Currently, the `Qdrant Web UI` page is nested under the API & SDKs section. Which doesn't seem right.
Also, we're already pointing to the API reference in the nav bar. So no need to again in the API & SDKs section.

docs: Re-organise API & SDKs, Web UI entries in the sidebar

---

qdrant-landing/content/documentation/concepts/vectors.md
qdrant-landing/content/documentation/data-management/spark.md

- Rephrases the Spark connector docs for simplicity.
- Fixes a typo in the named vectors snippet from yesterday.

docs: Misc updates to /frameworks/spark.md and /concepts/vectors.md

---

qdrant-landing/content/documentation/concepts/optimizer.md

The Qdrant documentation incorrectly describes a parameter named max_segment_number under the "Merge Optimizer" section, suggesting that this parameter controls the merging of small segments when their number exceeds a certain threshold. However, this parameter does not exist in the Qdrant codebase. Instead, the correct approach to managing segment size and merging is through the max_segment_size parameter, which determines the maximum size of a segment.
This discrepancy may have caused confusion among users trying to optimize their Qdrant instances, leading to ineffective configurations and potentially suboptimal performance.

Fix Documentation: Correct Segment Merging Description and Parameters in Qdrant

---

qdrant-landing/themes/qdrant-2024/assets/js/helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/segment-setup.js
qdrant-landing/themes/qdrant-2024/layouts/partials/js-head.html

Adding utm parameters (Google Ads tracking) from the url to outbound links going to product pages for cross domain analytics.

Gather utm params and add to outbound product links

---

qdrant-landing/config.toml
qdrant-landing/package-lock.json
qdrant-landing/themes/qdrant-2024/layouts/partials/js-head.html
qdrant-landing/themes/qdrant/layouts/partials/head.html
qdrant-landing/themes/qdrant/layouts/partials/table_of_content.html

- Fixes:
```console
ERROR deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use .Site.Config.Services.GoogleAnalytics.ID instead.
```
- I've also run: `npm audit fix`

fix: Use .Site.Config.Services.GoogleAnalytics.ID instead.

---

qdrant-landing/content/documentation/private-cloud/private-cloud-setup.md

* only release namespace
* list of namespaces
* all namespaces

Private Cloud: document different deployment scopes

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/mastra.md

docs: Mastra integration

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/camel.md

docs: Camel AI integration

---

qdrant-landing/content/documentation/guides/monitoring.md

While updating the Datadog integration with the new metrics, I found this page was not up-to-date.

docs: List hardware/memory metrics in /guides/monitoring.md

---

qdrant-landing/content/documentation/concepts/collections.md

[Rendered](https://deploy-preview-1355--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/collections/#grey-collection-status)
Tell users they may use the `Trigger Optimizers` button in the web UI to resolve a grey collection status. It's easier than manually sending a request.
I did not include an image in the documentation as I don't think it's necessary, but here is what I'm referring to and what it looks like:

For a grey collection status, hint to use the trigger optimizers button

---

qdrant-landing/content/community/community-features.md

As per [this issue](https://github.com/qdrant/qdrant/issues/5730), the contributors guide was moved to the `docs` repo [in July 2024](https://github.com/qdrant/qdrant/pull/4678).

Corrects contributors link

---

qdrant-landing/content/documentation/cloud/cluster-scaling.md
qdrant-landing/content/documentation/hybrid-cloud/hybrid-cloud-setup.md
qdrant-landing/content/documentation/hybrid-cloud/operator-configuration.md
qdrant-landing/content/documentation/private-cloud/configuration.md

Only merge, once operator v2 is the default for new environments for Hybrid Cloud.
Fixes https://github.com/qdrant/cloud-pm/issues/2097

Update hybrid cloud docs for operator v2

---

qdrant-landing/content/documentation/concepts/filtering.md

[Rendered](https://deploy-preview-1386--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/filtering/#has-vector)
Document new `HasVector` condition released in `v1.13.0`.
Examples have not been validated against the clients code yet :)

[docs] Document HasVector condition

---

qdrant-landing/content/documentation/cloud/cluster-scaling.md

[Rendered](https://deploy-preview-1406--condescending-goldwasser-91acf0.netlify.app/documentation/cloud/cluster-scaling/#resharding)
It is expected to enable cluster manager on all clusters - even if running a single node - some time later.
This updates the warning banner to explicitly state that somewhere.
At least for now that means resharding cannot be used on single node clusters. If customers are looking for this, we can recommend them to scale up their cluster first after which resharding will become available.

Resharding requires cluster manager, only enabled on multi node clusters

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

Fixes <https://github.com/qdrant/qdrant/issues/4626>
Rendered: <https://deploy-preview-1013--condescending-goldwasser-91acf0.netlify.app/documentation/guides/distributed_deployment/#write-consistency-factor>
This extends the write consistency factor description a bit. It improves on two points.
First, if a high write consistency factor is used an operation might fail to apply if there aren't enough active replicas. It now describes that the user is responsible for sending the operation again, to ensure a consistent state.
Second, this now describes that a lower write consistency factor may be used. In that case the write will be accepted if there are non-active replicas. Unresponsive replicas are marked as dead and are automatically recovered by the cluster to guarantee data consistency …

Extend write consistency factor text, reapply on client vs lower factor

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

The JSON example for `replication_factor` and `write_consistency` had extra comma `,` at the end which makes the JSON invalid. This PR removes those commas.

Fix JSON example for distributed deployment

---

qdrant-landing/content/documentation/embeddings/cohere.md

The original documentation page is using `client.search` which gives the warning
```bash
/var/folders/yq/g_nknqvs6tz0_nv06j3b5cth0000gn/T/ipykernel_17665/1253820733.py:1: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
client.search(
```
It's replaced with `client.query_points`

Replacing deprecated `search` with `query_points`

---

netlify.toml
qdrant-landing/config.toml
qdrant-landing/content/get_anonymous_id/_index.md
qdrant-landing/themes/qdrant-2024/layouts/get_anonymous_id/baseof.html

Going to be use this standalone page to allow cross-site passing of `ajs_anonymous_id` from parent (landing_page) to child (cloud ui). This is the first step in the process. Returning an `ajs_anonymous_id` if it exists. Only allowed from Cloud UI staging and production origins.
This path `/get_anonymous_id` will be used within the iframe in Cloud UI.
https://www.teamsimmer.com/2023/05/02/how-do-i-use-the-postmessage-method-with-cross-site-iframes/
*Also updating staging segmentWriteKey with most recent value as well as the development value which was not previously set.

get_anonymous_id 'page'

---

netlify.toml
qdrant-landing/config.toml
qdrant-landing/themes/qdrant-2024/layouts/get_anonymous_id/baseof.html

- The iframe was loading with 301, because it was missing the trailing slash
- Added localhost:3000 to Hugo's HTTP headers for path
- Remove domain checks, since we have CSP headers for protection
- Added development domain to headers, alongside staging and prod.

Improve headers and fix redirect for analytics iframe

---

qdrant-landing/content/documentation/concepts/hybrid-queries.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-closer-to-user/_description.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-closer-to-user/csharp.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-closer-to-user/go.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-closer-to-user/http.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-closer-to-user/java.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-closer-to-user/python.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-closer-to-user/rust.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-closer-to-user/typescript.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/_description.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/csharp.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/go.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/http.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/java.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/python.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/rust.md
qdrant-landing/content/documentation/headless/snippets/query-points/score-boost-tags/typescript.md

For v1.14 release
- Adds documentation for formula queries
- Removes `Re-ranking with payload values` section since formula queries can do the same thing, but more versatile.
[Rendered](https://deploy-preview-1506--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/hybrid-queries/#score-boosting)
TODO:

Docs: Score boosting

---

qdrant-landing/content/documentation/concepts/explore.md

[Rendered](https://deploy-preview-1531--condescending-goldwasser-91acf0.netlify.app/documentation/concepts/explore/#sum-scores-strategy)
Targeting v1.14 release.
Adds documentation for `sum_scores` recommendation strategy.
PR in core:
- qdrant/qdrant#6256

Docs: add `sum_scores` strategy section

---

qdrant-landing/content/documentation/beginner-tutorials/search-beginners.md

It feels that writing about how to launch python is a bit too much and should be a pre-requisite

remove too detailed instructions

---

qdrant-landing/content/documentation/fastembed/fastembed-colbert.md

Qdrant-client v1.14 adds implicit local inference.
This PR is a draft which adds code snippets showcasing how to use it without explicit embedding computation.

new: provide local inference examples in colbert docs

---

qdrant-landing/content/documentation/overview/_index.md

This pull request includes a minor correction to the documentation in the `qdrant-landing/content/documentation/overview/_index.md` file. The grammatical error "often using" was corrected to "often use" for improved readability and accuracy.
* [`qdrant-landing/content/documentation/overview/_index.md`](diffhunk://#diff-ce5b2e075462bfdbcfe5d0de4a281020cb168b46ebe16de7a5bba71c6978f4eaL55-R55): Fixed a grammatical error in the description of vector database optimizations.

Typo fix in _index.md

---

qdrant-landing/content/documentation/frameworks/_index.md
qdrant-landing/content/documentation/frameworks/honeyhive.md

This PR adds HoneyHive to the list of supported frameworks.  The guide contains step-by-step instructions for integrating HoneyHive with Qdrant, including installation, setup, and usage examples.

[Integration] - add HoneyHive framework documentation

---

.github/workflows/internal-dead-links.yml
qdrant-landing/content/articles/vector-search-resource-optimization.md

There is a corner-case in the link checker, that if we create a link with default base of localhost, link checker would think it is a valid one.
To prevent an obvious mistake, we can configure links checker to use base with non-standard port to make the accidental copy-paste of url less likely

use non-standart port for links checker

---

qdrant-landing/content/documentation/search-precision/reranking-semantic-search.md

Remove an extra colon in the documentation line.

docs: fix extra colon in documentation

---

qdrant-landing/themes/qdrant-2024/assets/js/helpers.js
qdrant-landing/themes/qdrant-2024/assets/js/segment-helpers.js
qdrant-landing/themes/qdrant-2024/layouts/partials/js.html

Marketing Team needs to be able to identify utm params and referrer for a new user's FIRST visit to the marketing site. We've done this implicitly in the warehouse but we need the information further upstream for Hubspot/CRM AND this will make even the downstream research easier and more reliable (ie not relying on JOINing many different tables in hopes of uncovering the true initial touch point with qdrant.tech).
Introducing isFirstPageView property in Page event and in new identity call for Marketing traffic source attribution

isFirstPageView for Marketing Traffic Source Attribution

---

qdrant-landing/static/llms.txt

This PR adds an `llms.txt` file to the `static/` directory so it will be served at `https://qdrant.tech/llms.txt`.
The file is intended for LLM agent and crawler discoverability, similar to `robots.txt`. It includes a summary of Qdrant and links to relevant documentation, APIs, and tutorials.

Add llms.txt for LLM discoverability

---

qdrant-landing/content/documentation/guides/distributed_deployment.md

We were missing HTTP snippets for creating custom shards for distributed deployment. I decided to add it and move all language snippets for creating custom shard into a dedicated snippet section. 
See https://deploy-preview-1851--condescending-goldwasser-91acf0.netlify.app/documentation/guides/distributed_deployment/#user-defined-sharding

Add dedicated section for creating custom shards in distributed deployment guide
